### ISSUE TITLE
Manage.sh does not work in a Mac

### ISSUE THREAD

**Issue by jmbenlloch** [next-exp/IC#107]
We have tried to install IC using `source manage.sh install_and_check 3.5` but `wget` is not installed, so miniconda is not downloaded and we cannot continue with the installation. 

It seems that curl is available in Mac, we should check if it installed by default in both Mac & Linux, in that case maybe we should change manage.sh to use curl.

**Comment by jacg** [comment]
I suggest that the script try one, and then, if necessary, the other. That way we further reduce the possibility of failure.

Just in case neither `wget` nor `curl` is available, then we should include an implementation of something equivalent written in pure `bash` in the `manage.sh` script :-)

**Comment by jacg** [comment]
#139 fixes this.

In the process we noticed that we do not handle 32 bit architectures, but we decided not to bother with that unless someone using one actually comes along.
