### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#126]
I would like us to state in writing what we have been saying off line:

**IC will be continuously delivered via the master branch in `nextic/IC`.**

Consequently, there will be no release branch, no release tags, etc.

Another consequence of this is that we must be *extremely* strict about keeping the master branch usable at all times.

Acknowledging this here should be enough for now, but eventually such a statement has to make it into the manual, so this issue should be closed automatically by the merge of the PR which adds the statement to the manual (unless we decide against continuous delivery).

**Comment by jjgomezcadenas** [comment]
I find the idea of CD very attractive. However, does that prevent tags? 

Tags may still be useful to mark the sate of the repository when a given production is launched, and thus I would use them associated to productions (not to releases). Does it make sense?
J

**Comment by jacg** [comment]
CD doesn't prevent tags, it just makes them much less useful, but

> Tags may still be useful to mark the sate of the repository when a given production is launched, and thus I would use them associated to productions (not to releases). Does it make sense?

Absolutely.

**Comment by jjgomezcadenas** [comment]
OK! Perfect. 

I wonder whether a “running development branch” makes sense to optimize the use of CD. 

The scenario is as follows. CD implies, indeed, very strict revision before accepting PR to main. This may result in a situation in which development sort of “accumulates”. In fact, right now united-cities has become what I would call a “running development branch”, and the notion appears to be useful, we can carry on developing and improving while leaving in this branch (and sprout off branches from there from eventual PR)… I wonder if this is not a hint that CD benefits from a main and a development branch… or maybe I am thinking in circles… just trying to understand the issue…

**Comment by jacg** [comment]
It definitely benefits from development branches. The question is whether it benefits from having a single special development branach, or whether a number of longer-lived, shared feature branches (such as the current `city-united` branch) suffice.

I think that a `development` branch is useful for things that are being collected, ready for inclusion in the next release. With CD, as soon as it's ready it gets released by merging into `master`, so the need for the development branch seems to be absent.

I would wait and see. If after some time we decide that a designated development branch is useful, we can try it. For now, I suggest we do without.

**Comment by jjgomezcadenas** [comment]
As a matter of fact, I was thinking more in the notion of “thematic, long-lived development branches” (a la united-city), so I think what you say goes in the same direction than my (rather thick) thinking…

**Comment by jacg** [comment]
Continuous delivery was repeatedly stated as a fact of IC during the workshop.
