### ISSUE TITLE
Test Irene._store_pmaps

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#128]
There is  (deliberate) bug in `Irene._store_pmaps` which in not picked up by any of our current tests.

+ [ ] Write a test that points out the bug.
+ [ ] Fix the bug.
+ [ ] Check whether the name can be used instead of the (magic) number.

**Comment by jjgomezcadenas** [comment]
This has been addressed and solved in last commit

**Comment by jacg** [comment]
"The last commit" is not very informative. Please provide some reference (link). A PR number should do. Failing that, a hash of the actual commit.

Please understand that even if you are writing these comments as emails or git commit messages, they end up as GitHub comments on issues and PRs, and we should use the full power of those, and their cross-referencing capabilities, to make it easier to follow what is going on.

**Comment by jmbenlloch** [comment]
@jjgomezcadenas was referring to PR #147. I have explained him how to make references between issues and PR's.

**Comment by jacg** [comment]
Thanks. Even better, would be to develop the habit of writing the appropriate magic incantations (fix #whatever, closes #whatever, etc.) in the commit or PR messages, which close and link related issues.

This one is a bit tougher, becasue you can't do it a posteriori, and I often forget myself before it's too late.
