### ISSUE TITLE
Cities init method arguments

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#143]
We need to discuss whether it is more convenient for the cities constructors to list just their own arguments and take the ones belonging to the classes they inherit from as keywords or to list them all and make it more explicit.

**Comment by jacg** [comment]
Please create a branch with the proposed change and link to it here so that we can compare and contrast the two approaches.

**Comment by gonzaponte** [comment]
In gonzaponte/citiesargs you can find a draft of the code for this issue (it is a couple of commits behind nextic/master, but I will rebase). I have made two things:
- Remove from base classes (SensorResponseCity, CalibratedCity, etc.) all arguments belonging to the classes they inherit from, keeping only those owned by the class.
- Remove from implementation classes (Diomira, Irene, etc.) all arguments belonging to the base classes. This means that some explicit constructors which only job was to call the superclass constructor are not needed, so they have been also removed. In the remaining ones, the call is reduced to a single line.

I have done this in separate commits so it can be easily reverted.

**Comment by jacg** [comment]
@jjgomezcadenas You and I should look at this with peras and make a decision.

**Comment by jjgomezcadenas** [comment]
Agreed, next week!
