### ISSUE TITLE
Splitting *core* in two directories (*core* and *reco*)

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#150]
The directory core lumps together rather different animals. I propose to split of core in two separate directories:
a) core which would keep what I think are really core modules: configure, core_functions, exceptions, log_config, random_sampling and system_of_units, mpl_f (plus testing modules and cython modules)
b) reco which would, for now, get all the rest: nh5, params, peak_functions, pmaps_functions, tbl_f, wfm_f, mctrk_f (plus testing and cython)
Opinons?

**Comment by jacg** [comment]
Seems reasonable.

I'll try to knock together a branch that does this, quickly.

**Comment by jacg** [comment]
How about moving `mpl_functions.py` to something like `plot`?

**Comment by jjgomezcadenas** [comment]
Yes i have thought of something like that. Perhaps util so that we can stick there some other utilities?

Enviado desde mi iPhone

**Comment by jacg** [comment]
`mctrk` seems not to be used anywere.

**Comment by jjgomezcadenas** [comment]
Let me check this before removing

Enviado desde mi iPhone

**Comment by jjgomezcadenas** [comment]
mctrk_functions.py contains functionality to draw MC tracks. Although no one is using this right now, I expect use very soon, with the new city being written by Alex. In general these are important plotting functions. They could stay in core. Alternatively, if we create a directory *plot* or *util* this module could be moved there.
