### ISSUE TITLE
Implementation inconsistency in pmaps_functions

### ISSUE THREAD

**Issue by neuslopez** [next-exp/IC#156]
Functions `S12df_select_event` and `S12df_select_peak` look like they should have symmetric implementations, but one uses the parameter of the lambda while the other uses the parameter of the outer function. Investigate if it is a bug and if so we need a test.

**Comment by jacg** [comment]
No tests fail when these functions are deliberately broken.

**Comment by jjgomezcadenas** [comment]
This should be fixed now.
