### ISSUE TITLE
Modifying the format of S2Si table

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#157]
Currently `S2Si` is being written to file as a "sparse table". This means the following. 

This is the representation in memory of `S2Si`: 
```
{0: [[1353, array([  7.88733907,  10.91102902,  15.70949351,   8.74186014,
            0.        ,   0.        ])],
  [1354, array([ 13.91424864,  22.49485269,  31.07545674,  22.1793893 ,
            6.21694207,   0.        ])],
  [1356, array([  9.93309068,  15.09844199,  14.55788197,   5.48848607,
            0.        ,   0.        ])],
  [1359, array([  0.        ,  10.83277617,  18.66492619,  15.41744935,
            0.        ,   0.        ])]]}
```
Notice that the array with energies contains a number of ceros. 

This is the table representation:
```
array([(0, 1820002, 0, 1353, 0,   7.88733912),
       (0, 1820002, 0, 1353, 1,  10.91102886),
       (0, 1820002, 0, 1353, 2,  15.70949364),
       (0, 1820002, 0, 1353, 3,   8.74186039),
       (0, 1820002, 0, 1354, 0,  13.91424847),
       (0, 1820002, 0, 1354, 1,  22.49485207),
       (0, 1820002, 0, 1354, 2,  31.07545662),
       (0, 1820002, 0, 1354, 3,  22.17938995),
       (0, 1820002, 0, 1354, 4,   6.21694183),
       (0, 1820002, 0, 1356, 0,   9.93309021),
       (0, 1820002, 0, 1356, 1,  15.09844208),
       (0, 1820002, 0, 1356, 2,  14.55788231),
       (0, 1820002, 0, 1356, 3,   5.48848629),
       (0, 1820002, 0, 1359, 1,  10.83277607),
       (0, 1820002, 0, 1359, 2,  18.66492653),
       (0, 1820002, 0, 1359, 3,  15.417449  )], 
      dtype=[('event', '<i4'), ('evtDaq', '<i4'), ('peak', 'u1'), ('nsipm', '<i2'), ('nsample', '<i2'), ('ene', '<f4')])
```

Notice that the table representation eliminates the entries with zeros. The original array can still be reproduced, since the indexes are kept. 

However:

1. The PMAPS tables are small
2.  Reconstructing the array from the indexes rather than just reading the full array from file may be inefficient and in any case painful.

*Thus, we intend to change the format to write in file the full array (ceros included).*
@jacg, @gonzaponte, @neuslopez please comment

**Comment by jacg** [comment]
I recommend that you decouple interface from implementation.

1. Decide what it is that you want to be able to do with these objects, what operations you want to be able to perform on them, how you want to interact with them.
1. Come up with a convenient and expressive interface for being able to do so.
1. Implement both backends behind the interface.
1. Decide which backend is better based on use, experience and measurement, rather than speculation.
