### ISSUE TITLE
Error in df_to_pmaps_dict when reading an empty file

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#178]
I have encountered a bug when trying to read back pmaps produced with the new pmap writer interface. For some reason, the file is empty, which means that the `read_pmaps` function in reco/pmaps_functions.py returns empty data frames. This causes the following error in df_to_pmaps_dict:
````
ValueError: Buffer dtype mismatch, expected 'int' but got 'double'
````
 I think by default, pandas Data Frames tend to use doubles, unless the data explicitly says otherwise. Therefore, the "event" column, which should be of type int, does not contain the type information. This causes the cython function to crash because it expects an int array.

Question:
1. What caused the empty file? The new pmap-writer interface or an external error? I think it is the latter. @jmbenlloch, can you confirm (file number 8)?

If nobody complains, I will create a new PR with a simple protection in `df_to_pmaps_dict` (as well as in `df_to_s2si_dict`) and a couple of new tests to ensure we don't fall into this trap again.

**Comment by jjgomezcadenas** [comment]
I think @jmbenlloch may not be available for a couple of days. Do you find the same problem with all files? 

I am quite puzzled because I added tests that checked both the writing and the reading back of the pmaps. Although I had no defence in case that the file was empty, so the protection and tests will surely help.

**Comment by gonzaponte** [comment]
> I think @jmbenlloch may not be available for a couple of days. Do you find the same problem with all files?

Just one file, that's why I think it was something unrelated to IC.

**Comment by jjgomezcadenas** [comment]
OK, please do add the protection and tests.

**Comment by gonzaponte** [comment]
The solution if have found is very unsatisfying... It basically consists of an explicit conversion to the desired types. In order to be clear, here is the new code:
````
    if df.empty:
        return all_events

    cdef int   [:] event = df.event.values.astype(np.int32)
    cdef char  [:] peak  = df.peak .values.astype(np.uint8)
    cdef float [:] time  = df.time .values.astype(np.float32)
    cdef float [:] ene   = df.ene  .values.astype(np.float32)
````

I had to do this because:
1. Cython does not allow you to declare types within an `if`statement. I have tried to put the cdef lines inside a`if not df.empty` statement, but it won't compile.

2. The cython function checks whether the types match or not even if the code won't be executed. I have tried to remove the `.astype(...)` conversions, but it crashes at run time because the types do not match.

Because this solution bothers me, I keep asking myself whether this is really necessary... We ***should not*** have to deal with empty files.

**Comment by jjgomezcadenas** [comment]
I agree! @jmbenlloch we should find a way to protect against empty files!

**Comment by jjgomezcadenas** [comment]
Progress here, @gonzaponte, @jmbenlloch?

**Comment by gonzaponte** [comment]
We coded a `try: ... except: ...` protection scheme in `Dorothea` which is the city that triggered this issue. Now it depends on whether we want to implement this protection within the `read_pmaps` function. My position here is that we should not, but it is open for discussion.

**Comment by jjgomezcadenas** [comment]
The new version of IC does not appear to include this protection. Will you please check and suggest where it should go?

**Comment by gonzaponte** [comment]
It is already implemented in KrCity:
````
        for filename in self.input_files:
            print("Opening {filename}".format(**locals()), end="... ")

            try:
                s1_dict, s2_dict, s2si_dict = self.get_pmaps_dicts(filename)
            except (ValueError, tb.exceptions.NoSuchNodeError):
                print("Empty file. Skipping.")
                continue
````

**Comment by jjgomezcadenas** [comment]
Sorry, of course1 This is the best place to implement that protection, I think (it is the city that worries about its own business, while the free functions do not need to). Thus, I think we can close this issue.
