### ISSUE TITLE
Travis auto cancellation

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#194]
We should switch this on for `nextic` (and for our own forks):

https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

**Comment by jjgomezcadenas** [comment]
Agreed! Who switches on nextic ? You or @jmbenlloch

**Comment by gonzaponte** [comment]
This is crucial, or I will eventually collapse Travis' queues with my countless mistakes...

**Comment by jmbenlloch** [comment]
I have activated it for nextic/IC both in branches & pull requests. It seems to be a beta feature, so say something if you find any odd behavior in your PRs. For the moment I'll close this issue.
