### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#201]
I encountered the following error trying to use command line options:

````
$ python cities/Dorothea.py -c config/dorotheaKr.conf -i /Users/Gonzalo/github/NEXTdata/Kr2016/data/3389/*.h5 -o ../../ICARO/KrDST.h5 -n 1000
-bash: /Applications/anaconda3/envs/IC3.5/bin/python: Argument list too long
````

This has nothing to do with python, but with the shell. Does anyone, particularly @jacg or @jmbenlloch, know a workaround to this?

My approach would be to use quotes around the `-i` argument and expand it with `glob`.

**Comment by jacg** [comment]
Hmm, I guess that it's the star buried in the middle of all that

> ... `3389/*.h5 -o` ...

which is responsible for giving you a very long arguement list. I can't tell from here, but I guess there must be quite a few files matching that pattern on your filesystem.

> My approach would be to use quotes around the -i argument and expand it with glob.

I suspect that would still leave you with the same fundamental problem: the argument list being too long! It doesn't matter how you compose it, if it's too long for bash to handle, then it's too long.

I guess that you need to process all those files in one go, so tricks using `xargs` and `find ... exec` won't work either.

Can you identify the files and list them in a config file, and feed the config file to the bash command line? (I forget how our config file parser deals with multiple input files.)

**Comment by jmbenlloch** [comment]
You can use simple quotes to prevent bash from making variables expansion. I've written a little program which only prints sys.arg. See:

```
jmbenlloch@laptop:~/next/dataic$ python /tmp/test.py dst_NEXT_v0_08_06_Kr_ACTIVE_7_0_7bar_*
['/tmp/test.py', 'dst_NEXT_v0_08_06_Kr_ACTIVE_7_0_7bar_MCRD_10000.root.h5', 'dst_NEXT_v0_08_06_Kr_ACTIVE_7_0_7bar_PMAPS_10000.root.h5', 'dst_NEXT_v0_08_06_Kr_ACTIVE_7_0_7bar_RWF_10000.root.h5']
jmbenlloch@laptop:~/next/dataic$ python /tmp/test.py 'dst_NEXT_v0_08_06_Kr_ACTIVE_7_0_7bar_*'
['/tmp/test.py', 'dst_NEXT_v0_08_06_Kr_ACTIVE_7_0_7bar_*']
```

**Comment by gonzaponte** [comment]
That is what I was thinking about, @jmbenlloch. I guess this is the only solution.

**Comment by jacg** [comment]
Can this be closed now?

**Comment by gonzaponte** [comment]
Yes
