### ISSUE TITLE
Cities inheritance structure

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#203]
I have noticed something in the inheritance chain of the base cities that may not be structurally correct.

All base cities inherit from City, which seems to be designed to work as the general manager which controls the job-related parameters (such as IO files, number of events, etc.), but it also holds information from the database. However, base cities do not care about IO at all as they simply provide tools and interfaces to handle the data. They may require, however, the database info, which is the reason they derive from City, I think. The merging of database- and IO-related stuff in City causes a lot of noise in the base subcities (recursively passing several parameters they don't care about to the constructors).

My proposal is to split City into two separate abstract cities, namely DatabaseCity (for run-related stuff) and IOCity (for IO stuff, obviously). This way, base cities can derive from DatabaseCity only and concrete implementations (Irene, etc.) can subclass **both** DatabaseCity and IOCity because these are the ones that actually use IO operations.

Hope it is clear, I have experienced some pain trying to explain myself properly.

**Comment by jjgomezcadenas** [comment]
I like this. What do you think @jacg?

**Comment by jacg** [comment]
Forming an opinion worth sharing would take far more time than I have available at present.

**Comment by jjgomezcadenas** [comment]
My opinion is then to postpone the split of the cities until I have some time to discuss with @jacg, since we have more urgent things to do, in particular to review Dorothea. Agreed, @gonzaponte?

**Comment by gonzaponte** [comment]
> Agreed, @gonzaponte?

Sure, I opened this issue just to start the discussion so that @jacg can meditate (because Jedis meditate) about it!

**Comment by jjgomezcadenas** [comment]
I believe most of this issues are addressed now.
