### ISSUE TITLE
Travis is failing due to fault installation of pytest-xdist version 1.15.0

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#205]
This is the error log.

Collecting hypothesis-numpy
  Downloading hypothesis-numpy-2.0.0.tar.gz
Collecting flaky
  Downloading flaky-3.3.0-py2.py3-none-any.whl
Collecting pytest-xdist
  Downloading pytest-xdist-1.15.0.tar.gz (87kB)
[?25l
[K    11% |â–ˆâ–ˆâ–ˆâ–Š                            | 10kB 9.7MB/s eta 0:00:01
[K    23% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ                        | 20kB 8.8MB/s eta 0:00:01
[K    34% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–                    | 30kB 6.9MB/s eta 0:00:01
[K    46% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ                 | 40kB 6.9MB/s eta 0:00:01
[K    58% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹             | 51kB 6.5MB/s eta 0:00:01
[K    69% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–         | 61kB 7.6MB/s eta 0:00:01
[K    81% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–     | 71kB 7.5MB/s eta 0:00:01
[K    93% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰  | 81kB 8.1MB/s eta 0:00:01
[K    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 92kB 4.4MB/s 
[?25h    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UVZkci/pytest-xdist/setup.py", line 37, in <module>
        'Programming Language :: Python :: 3',
      File "/home/travis/miniconda/envs/IC2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/travis/miniconda/envs/IC2.7/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 318, in __init__
      File "/home/travis/miniconda/envs/IC2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/travis/miniconda/envs/IC2.7/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 375, in finalize_options
      File "build/bdist.linux-x86_64/egg/setuptools_scm/integration.py", line 21, in version_keyword
      File "build/bdist.linux-x86_64/egg/setuptools_scm/__init__.py", line 118, in get_version
      File "build/bdist.linux-x86_64/egg/setuptools_scm/__init__.py", line 96, in _do_parse
    LookupError: setuptools-scm was unable to detect version for '/tmp/pip-build-UVZkci/pytest-xdist'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    
    ----------------------------------------
[31mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UVZkci/pytest-xdist/[0m

CondaValueError: Value error: pip returned an error.

All tests pass locally so we consider that the problem is in Travis... any opinion,  @jacg ?

**Comment by jacg** [comment]
Very quickly:

> All tests pass locally so we consider that the problem is in Travis

Without investigating, my guess would be that the problem is with the latest version of `pytest-xdist` that has been uploaded to PyPI, rather than anything to do with Travis per se.

I can think of two obvious workarounds:

1. Comment out `- pytexst-xdist` in the `make-environment` section in `manage.sh`.

2. Explicitly specify an older version of `pytest-xdist`.

We don't use `pytest-xdist` for anything critical: it's just a convenience for running tests in parallel. Last time I looked, our test suite was not large enough for this to offer any signifcant benefits. So we can perfectly live without it for the time being.

**Comment by jacg** [comment]
This seems to have sorted itself out, as expected.
