### ISSUE TITLE
Build broken, probably because of database change

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#208]
I just tried to push a trivial commit, and Travis/pytest gave 8 failures and 56 errors.

Rerunning builds which had passed earlier, now gives a similar failure.

Downloading the latest version of the database makes the tests fail in a similar way on my local machine.

Does anyone have a quick fix?

**Comment by jmbenlloch** [comment]
I am checking what happened to find out where is the error. Until we manage to fix it, maybe you can take the previous DB version and run the tests locally, You can download the file here: http://jobenllo.web.cern.ch/jobenllo/localdb.sqlite3
