### ISSUE TITLE
Rebase + merge --no-ff policy

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#211]
I would like to change our merge policy to the following:

+ All PRs must be rebased on top of `master`. (Just like we have been doing so far.)

+ The merge itself comes in two varieties:

  1. If the PR contains just one commit: `merge --ff`

   2. If the PR contains more than one commit: `merge --no-ff`, with a well-written commit message.

The point of this is 

1. To leave a record of the units of work that were done. Our current policy of always rebasing leaves no trace of which commits belong together, which commits came in the same PR. That's why we want the `--no-ff` merge for multiple-commit PRs.

2. To avoid spaghetti. That's why we should rebase before merging.

3. To avoid excessive noise. That's why single-commit PRs shouldn't have a merge commit. The appearance of a commit without a merge indicates that that commit was a unit, that it was the only commit in the PR. Marking such single commits with a merge commit is pointless noise.

The main problem I see with this is that I can't find how to persuade GitHub to help with this. (It looks quite easy in GitLab.)

**Comment by jjgomezcadenas** [comment]
I see no problem provided that we find a way to do it in GitHub + magit. If we need to do such things by hand, it will become messy...

**Comment by jacg** [comment]
>  If we need to do such things by hand, it will become messy...

Agreed.

I have merged #209 using this new policy. I used pure Magit, bypassing GitHub. It's easy, but it would be preferable if GitHub could be set up to guide the process.

I suggest you let me do all the merging of PRs for now (unless it's urgent and I'm not available) so that I can explore the possibilities, pitfalls, etc. Then we can decide whether we want to adopt it in the long term or not.

Related to this issue, in https://github.com/nextic/IC/commit/c338c6d6b19e0ba439ddde060fca37130cf287e9 I added a new option (`-p`) to the Magit log popup, for toggling the `--first-parent` option in `git log`.

This folds/unfolds the commits making up a multi-commit PR in the proposed policy, thereby giving you the choice of whether you see just the PRs, or each individual commit in the log.

You should probably add that line to your Emacs config file. Or just download the new version of the file, if your local copy doesn't contain any personal customizations.

**Comment by jacg** [comment]
This idea has proved popular, so we are accepting this as our standard policy. Please leave merging into `nextic/master` to @jmbenlloch & @jacg, or ask one of them to show you how to do it: we have not identified a way to do it in GitHub, so it must be done locally.
