### ISSUE TITLE
Spurious failures in test_corrections_1d 

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#234]
This test gives too many false negatives. This can probably be resolved by fiddling with the `flaky` parameters.

**Comment by gonzaponte** [comment]
I would like to solve this by generating data distributed according to some custom pdf with hypothesis. I haven't found anything about that in the documentation, so I will do it with fixtures unless someone finds another way.

**Comment by gonzaponte** [comment]
The solution of this issue is attempted in #241.

**Comment by jacg** [comment]
Fixed in #241.
