### ISSUE TITLE
Comment on Zaira parameters

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#242]
@gonzaponte we are revising the config files in `invisible_cities/config/` to prepare them for

+ use in *real* command line tests
+ documentation

Please comment.

Is there anything missing?

Note that we are wondering whether some of these entries are obsolete.

@jjgomezcadenas asserts that you have 10 s.

    # zaira.conf
    
    # Example configuration file for Zaira
    
    # Input files
    PATH_IN $ICDIR/database/test_data/
    FILE_IN dst_3389_test.h5
    
    
    # Change PATH_OUT to you output DIR
    PATH_OUT /tmp
    FILE_OUT run3389.corr
    COMPRESSION ZLIB4
    
    # Value for this run in ns
    LIFETIME   1e6
    
    # Run info
    RUN_NUMBER 3389
    
    # How frequently to print events
    NPRINT 10000
    
    # Zaira
    DST_GROUP DST
    DST_NODE  Events
    
    XBINS  100  # mm
    XMIN  -215
    XMAX  +215
    
    YBINS  100
    YMIN  -215
    YMAX  +215
    
    ZBINS   30
    ZMIN    75
    ZMAX   150
    
    Z_SAMPLING 10000 # obsolete ?
    FIDUCIAL_R   100
    FIDUCIAL_Z 0 200
    FIDUCIAL_E 3e3 1e4 # keV
    
    TBINS   100
    #TMIN     0 # obsolete ?
    #TMAX  1800

**Comment by jjgomezcadenas** [comment]
This should be clear now.
