### ISSUE TITLE
Event numbers stored in 32 bits

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#244]
In order to ensure unique event numbers in MC data, we have adopted the strategy of adding the Python hash of the data filename base to the local event number, provided by the Nexus generation. This means that if the event numbers in MCRD (Nexus) files start at 0 for each file, then Diomira-generated files (RWF) start at `hash(filename) + local_event_number`.

To reduce the probability of collisions, we want to store these numbers as unsigned 64-bit integers. We have changed the corresponding run and event table in `nh5.py` to reflect this, but, for some reason we have not been able to track down yet, this number is mangled if it exceeds the limits imposed by 32 bits.

For now we have limited the hash generation to avoid such large numbers, but this needs to be fixed.

**Comment by paolafer** [comment]
I've realized only now that I'd been assigned this issue, sorry! I think it can be closed, since now MC events come with unique numbers within the same production.
