### ISSUE TITLE
Some S2s and their corresponding S2Sis are not the same length

### ISSUE THREAD

**Issue by abotas** [next-exp/IC#249]
Looking at pmaps of Na montecarlo data I have found events with S2s (pmt S2s) and S2Sis (sipm S2s) of different length. I am not sure if this is a bug or if it is allowed, but it is problem because we do not record the times in the S2Si as we do in S2. (When there is a clear 1-1 mapping between S2 and S2Si values this is no problem)
Since we don't have the times of the S2Si, reconstructing z-coordinates of clusters is not possible. 

@gonzaponte told me he has run into this problem as well. 

I will look into this more but wanted to raise the issue first just in case someone knows what is going on / there is something I am misunderstanding.

**Comment by jjgomezcadenas** [comment]
Ale, intentamos hablar de esto esta noche, OK?

**Comment by abotas** [comment]
sounds good!

**Comment by abotas** [comment]
resolved with new pull request rebin waveform
