### ISSUE TITLE
Too many things called S2

### ISSUE THREAD

**Issue by abotas** [next-exp/IC#262]
If no one tells me not to, I will make a quick, tiny PR to solve this:

We have a variable in the code, S2, that means different things in different places. These idiosyncrasies are not a big deal I tried to ignore them, but now as reuse IC functions/objects the ambiguity infects the code I am developing. 

1) In the majority of places in the code, we call S2: a dictionary mapping peak numbers (keys) to their respective peaks, S2 times and S2 pmt energies np.arrays.

2) However, we in reco.params.py, in PMaps, we call S2 a a dictionary mapping event number to the dictionary described in 1). 

3) And, in reco.peak_functions, in sipm_s2_dict() and sipm_s2(), we call S2 one peak containing the times and pmt energies, from one event. (In these two functions the S2 described in 1) is called S2d).

I SUGGEST:
a) in reco.params PMaps should contain S1s, S2s, and S2Sis instead of S1, S2, Si.

b) we distinguish between the dictionary containing the various S2 peaks for an event and a single S2 peak in an event. There are a couple different ways we can do this. 

Any input, particularly suggestions as to how to implement b) would be very much appreciated. I'm starting to feel bad for our pobres enemigos. They are hopelessly lost now...

**Comment by jjgomezcadenas** [comment]
Agreed, pobres enemigos!

To complicate matters further, we also call S2 (in event_model.py) the high level interface!!!
So a way out of it is:

PMaps as you should S1s, S2s, S2Sis.
S1, S2 and S2Si ---> instances of high level class (in event_model.py)
dictionary of peak number (key) to peak --> S1d, S2d, S2Sid. 
The individual elements of the S1/S2 should be called peaks, where needed.

Does this help??

**Comment by abotas** [comment]
Yes, sounds good. I put this in a tiny PR

**Comment by jjgomezcadenas** [comment]
All this is addressed in #265
