### ISSUE TITLE
Cecilia city

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#264]
I've started debugging cecilia and I've found a minor issue of clarity. 
The parameter data_mc_ratio is actually MC/data, as I deduce from how it is used in the code. Shouldn't we call the parameter mc_data_ratio?

**Comment by jjgomezcadenas** [comment]
Yes, I see no problem to do that. Go for it, prepare a PR with the name change.

**Comment by jjgomezcadenas** [comment]
I will include this change in the on-going revision I am making in cities, you don't need to do it.

**Comment by paolafer** [comment]
I'm doing other changes to cecilia, since I've found other problems. Let me do all the modifications to cecilia, is that ok?

**Comment by jjgomezcadenas** [comment]
yes, you have the floor

**Comment by jjgomezcadenas** [comment]
Cecilia has been (provisionally) deleted, since it contained mixed functionality (it was partially a simulation city and partially a processing city). The plan is to extend Diomira so that in addition of simulating the electronics is capable of simulating the trigger.
