### ISSUE TITLE
Weird sipm signal after Diomira

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#266]
@jmbenlloch and @abotas have noticed that the signal in the tracking plane after passing through diomira does not make sense, as shown in [here](https://github.com/jmbenlloch/ICARO/blob/master/icaro/MC/MC_mapping.ipynb).

I will investigate further.

**Comment by gonzaponte** [comment]
I suspect this bug has nothing to do with the code. The notebook demonstrating this effect uses some display that can be misleading (integrate of the sipm response). If I plot the actual waveform of one of the relevant sipms, it makes sense, as shown in this picture.
![image](https://user-images.githubusercontent.com/8233521/28034812-99c5ca20-65b2-11e7-8920-b8f3dd1703f2.png)
On the other hand, if I plot the waveform of one of the weird sipms in the nb I see this:
![image](https://user-images.githubusercontent.com/8233521/28034672-25c48b2a-65b2-11e7-9a5e-8ae43acd5b1c.png)
which makes me think the problem is in the pdfs of the SiPMs. Have you updated them @jmbenlloch ?

**Comment by gonzaponte** [comment]
I think I have found the problem. I took a look at the pdf of the "noisy" SiPM in the previous comment and it looks like this:

![image](https://user-images.githubusercontent.com/8233521/28065736-3b9655f4-663a-11e7-8dbe-809d2c37e47e.png)

Having up to ~20 pes of noise is unrealistic, but I don't know where is this coming from (something went wrong during the calibration? is the SiPM just not working properly?).

What are we going to do? In my opinion, the right thing to do is to mask these sensors with Active=0. What do you think @jjgomezcadenas @jmbenlloch?

**Comment by jjgomezcadenas** [comment]
Guys, there are two things to do: One is to implement in Diomira the capability of masking sensors (and propagate that to the other cities, though the data base). The second thing is to check with Andrew to find out it the wrong sensors are under control (e.g, are they bad sensors or did something go wrong with the last calibration)?

@gonzaponte, @jmbenlloch you have the floor

**Comment by gonzaponte** [comment]
I agree. I am working on the first point.

**Comment by jjgomezcadenas** [comment]
Is this already understood?

**Comment by gonzaponte** [comment]
Yes, this is addressed in #268. We still have to:
1. Monitor sipms pdfs coming from calibration.
2. Update the database masking the noisy sensors.

The first point is not relevant for this issue, but I wanted to list it so we don't forget. Is the second one already addressed, @jmbenlloch?

**Comment by jjgomezcadenas** [comment]
Is this solved, @gonzaponte, @jmbenlloch ?

**Comment by gonzaponte** [comment]
A tiny production has shown agreement between twf and rwf. @jmbenlloch wants to propagate the changes in the database required for this check to the official db and recheck with the small production we are going to use for debugging.

**Comment by jjgomezcadenas** [comment]
I think this is fixed. New productions seem OK.
