### ISSUE TITLE
type hint:

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#282]
I propose that we start to use type hints seriously: 

For example:

    @staticmethod
    def valid_peak(peak : Peak,
                   energy : minmax, width: minmax, height : minmax) -> bool:
        """Returns True if the peak energy, width and height
        is contained in the minmax defined by energy, width and
        height.

        """
        f1 = energy.contains(peak.total_energy)
        f2 = width.contains(peak.width)
        f3 = height.contains(peak.height)

        return f1 and f2 and f3

    @staticmethod
    def select_valid_peaks(s12 : S12,
                           energy : minmax, width: minmax, height : minmax) ->List[int] :
        """Takes an s1/s2 and returns a list of peaks that are contained
        within the boundaries defined by energy, width and height.

        """

type hints allow us to document the functions explaining the types they expect and what they return. Type hints are ignored by python, but can be used by external packages such as mypy (although I am not sure that mypy likes cython). However, even if used only for documentation purposes I think it helps. 

See:

http://www.daveoncode.com/2017/03/06/writing-better-software-with-python-3-6-type-hints/
http://mypy-lang.org/index.html

And the referenced PEPS.

Your opinion, @jacg??

**Comment by jacg** [comment]
Sounds good. But please specify Duck Types rather than concrete types wherever sensibly possible.

**Comment by jjgomezcadenas** [comment]
OK, then if everybody agrees, @abotas, @gonzaponte, @paolafer, @jmbenlloch, @jerenner, @jacg let's try to write all new functions with type hints. 

http://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html
http://mypy.readthedocs.io/en/latest/kinds_of_types.html
http://mypy-lang.org/examples.html

**Comment by jacg** [comment]
Not sure what to do with this issue. Shall we keep it open until this directive is included in some coding standards document? Shall we task a junior contributor with adding type hints everywhere? Shall we just assume that we have got the message, and close the issue?

**Comment by jjgomezcadenas** [comment]
I am extensively using type hints, but I believe the practice has not gotten across yet. However, keeping open the issue is not gonna help. It needs to be redirected to a coding document. Thus I am closing it for new.
