### ISSUE TITLE
MC true information

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#287]
I'm looking at a file of pmaps produced recently (last week) with irene, starting from a RWF file that @jmbenlloch gave me, and it looks like only the information of the first event is saved. I remember that it was an issue @jerenner and I were having a couple of months ago in Geneva, hasn't it been solved yet? It is quite important to have true info in order to understand the performance of corona and paolina.

**Comment by jjgomezcadenas** [comment]
I think the events are saved by the event_indx is always zero. I will investigate today, if I can, before travelling. Otherwise @jmbenlloch, try and take a look, it must be a trivial problem.

**Comment by jjgomezcadenas** [comment]
Hola, I confirm that there is a problem with the index of the MC (e.g, MC number). 

1. The MC index (number) in MCRD files starts at 0 and runs sequentially (0, 1, 2, ...) the MCRD files appear to be correct.

2. In the RWF (after DIOMIRA), we have written a "generated number" (obtained from the file name), which does not change. So there is a bug somewhere (we should be adding the MCRD index, to have a sequence of numbers).

3. In the PMAPS all the indexes are cero (so there is a second bug).

Please @jmbenlloch investigate and fix.
