### ISSUE TITLE
Wrong definition of rms in barycenter

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#288]
In the `barycenter` function coded in [invisible_cities/reco/xy_algorithms.py](https://github.com/nextic/IC/blob/f5aef7b8b58f3173e52ee17eb979122dd1a6fd07/invisible_cities/reco/xy_algorithms.py) we have:
```
std = np.average((pos - mu) ** 2, weights=qs, axis=0)
```
Which is the variance, not the standard deviation. I think this is not intented, but correct me if I am wrong.

**Comment by paolafer** [comment]
@abotas and I were wondering a good while on this, once, and in the end we concluded that the way this code is used in IC is correct. If one should change the name of the variable, that is another issue ...

**Comment by gonzaponte** [comment]
> the way this code is used in IC is correct.

Where is it used?

**Comment by jjgomezcadenas** [comment]
Yes its the variance and treated as such in all parts of the client code... but the name is wrong!

Enviado desde mi iPhone

**Comment by jjgomezcadenas** [comment]
Precisely. Correct use wrong name

Enviado desde mi iPhone

**Comment by jjgomezcadenas** [comment]
Look in the tests

Enviado desde mi iPhone

**Comment by gonzaponte** [comment]
In my opinion, using the standard deviation is more appropriate than the variance, but as long as we are consistent it is fine with me. This affects the Cluster class as well, which has everything named std.

**Comment by jjgomezcadenas** [comment]
@gonzaponte can you submit a PR where all the (wrong) "std" names are consistently changed to "var" names?
