### ISSUE TITLE
I think cpf.correct_s1_ene(s1.s1d, csum) in PmapCity doesn't do anything anymore

### ISSUE THREAD

**Issue by abotas** [next-exp/IC#296]
I could be wrong but I've checked for some events and I think this line of code doesn't do anything anymore. line 524 in base_cities.PmapCity.pmaps

`s1 = cpf.correct_s1_ene(s1.s1d, csum)`
I think the input s1 and output s1 are the same is this true?

Can we get rid of it? or am I missing something?

**Comment by jjgomezcadenas** [comment]
Yes it doesn’t do anything anymore, a fossile!

**Comment by jjgomezcadenas** [comment]
Ale, please, submit PR to get rid of this fossil.

**Comment by jjgomezcadenas** [comment]
@abotas please, submit PR to get rid of this fossil.

**Comment by jjgomezcadenas** [comment]
Fixed
