### ISSUE TITLE
Module names do not conform to PEP8

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#31]
[PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) suggests that

> Modules should have short, **all-lowercase** names.

advice which IC does not follow at present. If we are going to follow this advice, we should probably make the change before opening up the repository to the rest of the team.

**Comment by jjgomezcadenas** [comment]
OK for me. Shall we prepare a list of modifications needed?

**Comment by jacg** [comment]
Not sure that we need a list, I would just create a branch and go for it.

As the module names change, the tests should point out what breaks, and thus guide you to what needs to be done. Then it's just a question of carrying on until

1. All modules have short, all-lowercase names,

2. all the tests pass.

It's on my TODO list, but about 2 hours from now I will be away from my computer for about 4 days, so I won't get around to it for a while. Feel free to try it. If nothing else, it will reinforce your appreciation of tests.

But if you want to make a list, we could do that too.

**Comment by jjgomezcadenas** [comment]
Done. Names in IC modules should now follow PEP8 standard.
