### ISSUE TITLE
Many warnings while running tests

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#310]
Starting at version 3.1 pytest displays warnings that were raised during the tests' excution.

Our test suite produces a few screenfuls of warnings. These need to be analyzed and

1. if the warning points at an error in our code, the code needs fixing

2. if the warning is a false positive, the code needs to be rewritten in a way that silences the warning.

**Comment by gonzaponte** [comment]
They are, mainly, attempts to operate with empty arrays or divisions by 0. We handle this situation in the code *after* the warning is issued. We do that because numpy returns `nan` in those cases. I see two options:
1. `np.warnings.filterwarnings('ignore')`, which I don't think you will approve.
2. define functions that handle these cases. For instance, we could define and use `mean_handle_empty` instead of `np.mean`.

What do you think?

**Comment by jacg** [comment]
> They are, mainly, attempts to operate with empty arrays or divisions by 0. We handle this situation in the code after the warning is issued. 

Have you any idea how ugly the code would get if we tried to prevent the situation from arising in the first place?

> `np.warnings.filterwarnings('ignore')`, which I don't think you will approve.

How did you guess?

> define functions that handle these cases. For instance, we could define and use `mean_handle_empty` instead of `np.mean`.

Much better!

**Comment by gonzaponte** [comment]
Well, I must admit, that I find not very pleasant to define functions such as
```
def mean_handle_empty(array):
    return np.mean(array) if array.size else np.nan
```
Because numpy already does this check internally (and it can actually handle empty arrays), only that it does issue a warning. But I guess there is no other option.

**Comment by jjgomezcadenas** [comment]
Not obvious to me. Perhaps we can live with the warnings specific to this type of issue, no?

**Comment by jacg** [comment]
> Perhaps we can live with the warnings specific to this type of issue, no?

No! Absolutely no way!

Having screens full of warnings go past every time you run the code, desensitises you to all sorts of messages and drowns out any signal that there might be buried in the noise. Sooner or later this causes you to miss something important.

**Thou shalt heed warnings and either fix the issue to which they alert you, or silence the false positive.**

(I'm still extremely pissed off that we have no way of suppressing the noise that Cython and Numpy conspire to generate during the compilation of our Cython functions. I wonder what dragons lurk there.)

**Comment by jjgomezcadenas** [comment]
Amen.

**Comment by jacg** [comment]
> `np.warnings.filterwarnings('ignore')`, which I don't think you will approve.

I'm trying a more fine-grained version of this ... but strange things are happening. Anyway, I hope to be able to avoid having to write stuff like

    return np.mean(array) if array.size else np.nan

so don't waste your time on doing stuff like that, for now.

**Comment by gonzaponte** [comment]
Actually, I am almost done with that...

**Comment by jacg** [comment]
Which version? filter warnings, or change the functions?

**Comment by gonzaponte** [comment]
The functions

**Comment by jacg** [comment]
Well, OK, stick it in a PR. If I ever get the filtering to work satisfactorily we can compare and pick the one we prefer.

**Comment by jacg** [comment]
OK, I'm convinced that the targeted filtering apporach is not going to work satisfactorily. Go ahead with yours.

**Comment by gonzaponte** [comment]
By the way, half of the warnings were coming from float overflows. Setting limits to hypothesis solves it, so it does not need fixing the code, just the tests.

**Comment by jacg** [comment]
> But first you need to change nmax to -1 in the configuration file, because the command line option is not working.

Which means that the command line options need to be fixed first. Let's see if I can find the time to do it tomorrow.
