### ISSUE TITLE
pmap constructors should do something smart when they are initialized with empty dicts

### ISSUE THREAD

**Issue by abotas** [next-exp/IC#315]
Right now I think they all build empty pmap classes. 

the best thing I can think to do is to have them raise an icexception if initialized with empty dicts. In this case we would also have to change code in other places to catch the exception. This should speed up pmap cities a little. But it's not backwards compatible in the sense that people making pmaps using peak/pmap functions in a notebook, for ex, would have to change their code a little bit. But i don't think many of us are doing that. 

My plan is to open a PR to do that^ unless someone complains or has a better idea!

**Comment by gonzaponte** [comment]
>  is to have them raise an icexception if initialized with empty dicts

I don't know what you mean. What is the point in not letting the user initialize them as empty? 

> This should speed up pmap cities a little

How?

**Comment by abotas** [comment]
I mean in the classes S1, S1Pmt, S2Si, etc we can immediately raise an exception if they are initialized with empty dictionaries. I cant think of how they could be useful empty, and maybe by immediately raising an exception we avoid some overhead, at least by avoiding initializing all their base classes. 

In `irene--> PmapCity.pmaps --> peak_functions_c.find_s1/s2/s2si`, 
For each event:
1) we construct an instance of S1, S2, AND S2Si, even if there is no s2 (for example) in that event.
2) Then we send an s1, s2, AND s2si to the pmap writing functions and 
3) the write functions call the store method, and for the empty s-whatevers the store function writes nothing.

(^Unless there is something i dont understand)

My plan would be to raise exceptions, catch them in pmap city, pass `None` to these writers for empty s-whatevers, then only try to store peaks that exist for those events. 

It seems like this should get rid of a little overhead, and a little more when we start collecting/writing ipmt peaks. and even if it didn't, passing around these empty objects seems unideal.

**Comment by gonzaponte** [comment]
Ok, I see. I don't think raising an exception is necessary, though. For me, rearranging the code so it does not generate empty instances is enough (and great!). I might be thinking about a non-existing case where it is useful to have the flexibility of empty classes, so I would like to hear what the bosses have to say.

**Comment by abotas** [comment]
We can definitely avoid exceptions if we want. But with the way the classes are implemented now pmap class instances really need to be replaced to be changed, so empty instances i dont think can be useful.

For ex: If you have an empty s2, and then say s2.s2d = {peak1:blah, peak2:balh}, and then say s2.peaks[peak1], you will get a key error even though you've filled s2d. This is because s2.peaks is created in the initialization of s2, so s2.peaks would be an empty dictionary. But maybe this is a separate issue..

**Comment by jjgomezcadenas** [comment]
I think rising an exception when init with empty dict (something that should not happen) is mandatory...:)
