### ISSUE TITLE
icusers in canfranc are not seeing when their jobs have crashed

### ISSUE THREAD

**Issue by abotas** [next-exp/IC#319]
icusers have rerun IC-dev in canfranc over a few different runs and isotopes now. The the dev irene version of irene has been run tens of thousands of times and crashed probably hundreds of times. But no one knew this was happening. We send the jobs to a queue system so maybe the prints and errors are being written to a file somewhere? Even if the output is written somewhere i guess no one is seeing it. 

Is there any way people running productions in canfranc can see (without too much pain and suffering) if any of their jobs have crashed?

**Comment by jjgomezcadenas** [comment]
This is a vert imporrtant point. Comments @jmbenlloch?

**Comment by abotas** [comment]
I should also mention i've hacked together the fix for IC-dev in canfranc and run a couple small productions check my [PR](https://github.com/nextic/IC/pull/320) fixed the bug and to make sure anyone runs anymore dev productions in the immediate future doesn't lose events to this bug. 

So IC-dev in canfranc has been quick fixed, but now IC-dev in canfranc is not consistent with any version of nextic/IC

**Comment by gonzaponte** [comment]
The output of the jobs is stored, although it is currently saved in an obscure and painful way. The name of the log file is of the form `.oXXXXXX`. Notice the `.` at the beginning, making it difficult for the enemy to find the file. This should be fixed in the `irene_prod.py` script by JM.

And, since we are talking about that, I propose a new repository in the IC family where we store and version these production scripts, configuration files, etc. What do you think, @jjgomezcadenas? you can come up with a good acronym, maybe referring to some Greek goddess or something like that ;)

**Comment by abotas** [comment]
The `.` is very sneaky... I didn't see the files.

**Comment by abotas** [comment]
Still, I agree that it would be nice to make this more obvious. Also for large runs there are many of these `.0XXX` files and you have to do a lot of scrolling to search them entirely. If it is easy to add something that tells us if and where there was a crash i think that would be very helpful. 

Otherwise we are responsible for searching through at least a few of these log files to check for crashes.

**Comment by gonzaponte** [comment]
When there is an error, a `.eXXXXX` file should be produced, I think. After that, it is easy to check whether it has been a crash or not.

**Comment by abotas** [comment]
Ahhh ok, that makes things much easier! In that case at least when we run the IC-dev repo we need to check to make sure there are none of those files. Who else is running IC-dev and needs to know this? At least @jerenner

**Comment by jjgomezcadenas** [comment]
Agreed we need a repo to store prod. Ugly name: icprod. Pretty name: Ceres (Godest of Earth). Vote.

**Comment by gonzaponte** [comment]
I haven't found a good name with "IC" in the name. I like Ceres.

**Comment by abotas** [comment]
Me too ceres!

**Comment by jjgomezcadenas** [comment]
I think this is solved
