### ISSUE TITLE
RuntimeWarnings in test_rebin_wf2

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#33]
In Python 2 `test_rebin_wf2` typically gives 3 `RuntimeWarning`s; in Python 3 the same test typically gives about 100 such warnings!

This could well be a symptom of a failure to deal correctly and completely with the differences in division between Python 2 and 3.

In any case, someone who understands what the test tries to achieve should

1. figure out whether these warnings are a symptoms of a bug

2. silence them.

**Comment by jjgomezcadenas** [comment]
I can look into this.

**Comment by jjgomezcadenas** [comment]
Can you tell me how to generate run time warnings?

**Comment by jacg** [comment]
> Can you tell me how to generate run time warnings?

`pytest -s`

By default pytest captures standard output, and only presents it for failing tests, along with their failure reports. The `-s` option is a shorthand for `--capture=no`

**Comment by jjgomezcadenas** [comment]
issue is fixed now, solution in the upcoming pull request

**Comment by jacg** [comment]
Fixed by commit bfcd897a1c843c381c696e309a79d20416a2c1b2
