### ISSUE TITLE
Managing productions

### ISSUE THREAD

**Issue by jmbenlloch** [next-exp/IC#335]
As pointed out by @gonzaponte  in issue #319 we should create a new repository for the scripts & configurations used both in data and MC productions. In that thread people's vote went to 'Ceres', so in principle that will be the name.

We will need to create tags both in nextic and in ceres to keep track of the versions (both code & configs) used to process data. For IC we could go with semantic versioning (http://semver.org/):

Given a version number MAJOR.MINOR.PATCH, increment the:

    MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards-compatible manner, and
    PATCH version when you make backwards-compatible bug fixes.

As we are not stable yet (but close to it), maybe could start now with 0.9.0.

For tags in ceres, unless somebody has a better proposal, we could use a human-readable date (this discards unix timestamps). I propose yyyy-mm-dd (example, today: 2017-09-08), in this way the lexicographical ordering is the same as the chronological one.

The files processed will have these versions as part of their filenames, so we know the versions used.

Opinions?

**Comment by jjgomezcadenas** [comment]
@jmbenlloch  Agree with the scheme, perhaps tags in CERES should include a key to indicate whether the production is data or MC, so dd-yyy-mm-dd or mc-yyy-mm-dd. Please proceed.

**Comment by jjgomezcadenas** [comment]
@jmbenlloch please go ahead, create directory, set tag, and close this

**Comment by jmbenlloch** [comment]
This is done already in https://github.com/nextic/CERES
