### ISSUE TITLE
Large number of warning when running tests in new installation 

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#338]
I have a new IC installation (new MAC), everything has run OK but I get a very large number of warnings:

Could the relevant suspects (e.g, @gonzaponte mainly) take a look and comment? Thanks!

=============================== warnings summary ===============================
invisible_cities/cities/zaira_test.py::test_zaira_KrMC
  /Users/jjgomezcadenas/Projects/IC/invisible_cities/reco/corrections.py:84: RuntimeWarning: invalid value encountered in true_divide
    self._fs = f_ref / self._fs
  /Users/jjgomezcadenas/Projects/IC/invisible_cities/reco/corrections.py:85: RuntimeWarning: invalid value encountered in true_divide
    self._us = self._fs * np.sqrt((self._us / input_fs)**2 +
  /Users/jjgomezcadenas/Projects/IC/invisible_cities/reco/corrections.py:86: RuntimeWarning: invalid value encountered in double_scalars
    (   u_ref / f_ref   )**2 )

invisible_cities/core/fit_functions_test.py::test_fit[fn3-pars3]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/scipy/stats/stats.py:4544: RuntimeWarning: invalid value encountered in true_divide
    terms = (f_obs - f_exp)**2 / f_exp

invisible_cities/core/fit_functions_test.py::test_profile1D_custom_range[func0-xdata0-ydata0]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
    arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)

invisible_cities/core/fit_functions_test.py::test_profile1D_custom_range[func1-xdata1-ydata1]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
    arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)

invisible_cities/core/fit_functions_test.py::test_profile1D_full_range_x[func0-xdata0-ydata0-xrange0]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
    arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)

invisible_cities/core/fit_functions_test.py::test_profile1D_full_range_x[func1-xdata1-ydata1-xrange1]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
    arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)

invisible_cities/core/fit_functions_test.py::test_number_of_bins_matches[func0-xdata0-ydata0]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
    x = um.multiply(x, x, out=x)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
    arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)

invisible_cities/core/fit_functions_test.py::test_number_of_bins_matches[func1-xdata1-ydata1]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
    x = um.multiply(x, x, out=x)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
    arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in true_divide
    ret = ret.dtype.type(ret / rcount)

invisible_cities/core/fit_functions_test.py::test_empty_dataset_yields_nans[func0-xdata0-ydata0]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
    arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)

invisible_cities/core/fit_functions_test.py::test_empty_dataset_yields_nans[func1-xdata1-ydata1]
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
    arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
  /Users/jjgomezcadenas/miniconda/envs/IC3.6/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============= 263 passed, 1 skipped, 46 warnings in 31.51 seconds ==============
Closing remaining open files:/Users/jjgomezcadenas/Projects/IC/invisible_cities/database/test_data/electrons_40keV_z250_RWF.h5...done
IC$

**Comment by gonzaponte** [comment]
Is this with the current master? Those warnings were fixed in #312.

**Comment by jjgomezcadenas** [comment]
Sorry, forgot to update. All is clear now.
