### ISSUE TITLE
Missing parameter reco_algorithm 

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#339]
I've noticed that the Penthesilea's parameter reco_algorithm has been killed. I haven't follow the whole discussion, so maybe I've missed something, but why has it happened? My understanding is that we want people to be able to try different algorithms, which can be chosen via a configuration parameter. Is this possible in the current code?

**Comment by jjgomezcadenas** [comment]
Well, there were only two algorithms and one was a particular case of the other. You can still run barycenter by setting negative lm_radius. Look at the config files in config, for example
dorothea_kr_with_barycenter...

**Comment by paolafer** [comment]
I was not thinking about the barycenter, but a possible different algorithm. 
However, also in the case of barycenter, I see two possible issues. The first one is that it doesn't seem intuitive to me that a negative lm_radius in corona means a barycenter. It seems completely arbitrary. 
The second one is about possible configuration parameters in the barycenter algorithm itself. We have seen in the past that the algorithm works better putting a cut on the charge of the SiPMs, for instance at a given ratio with the maximum charge. In the current configuration it is not possible to do that, because these parameters should be passed to the corona algorithm, too.

**Comment by jjgomezcadenas** [comment]
> was not thinking about the barycenter, but a possible different algorithm.

we cross that river when it comes.

> However, also in the case of barycenter, I see two possible issues. The first one is that it doesn't seem intuitive to me that a negative lm_radius in corona means a barycenter.

But it is documented, so not an issue.

> The second one is about possible configuration parameters in the barycenter algorithm itself. We have seen in the past that the algorithm works better putting a cut on the charge of the SiPMs, for instance at a given ratio with the maximum charge. In the current configuration it is not possible to do that, because these parameters should be passed to the corona algorithm, too.

When (if) we have the specific case we can work it out. Passing parameters should be simple enough.

**Comment by paolafer** [comment]
> we cross that river when it comes.

Well, we changed a code that allowed multiple algorithms to the current one, so what was the reason for that?

> But it is documented, so not an issue.

Ok, let's call it a suggestion, then.

> When (if) we have the specific case we can work it out. Passing parameters should be simple enough.

I think that the case is there: the barycenter algorithm reconstructs better when a selection of the SiPMs is made previously, based on the ratio of the SiPM charge over the SiPM with maximum charge.

**Comment by jjgomezcadenas** [comment]
> Well, we changed a code that allowed multiple algorithms to the current one, so what was the reason for that?

Simplicity. Both algorithms were the same.

> I think that the case is there: the barycenter algorithm reconstructs better when a selection of the SiPMs is made previously, based on the ratio of the SiPM charge over the SiPM with maximum charge.

Why on Earth do you want to mix the barycenter algorithm with a selection? Write a function that selects the SiPMs you want, then call barycenter with those SiPMs.

**Comment by jacg** [comment]
@jjgomezcadenas Could you please prepend `>` to text that you are quoting? The fact that things you quote and things you are saying look identical in your posts, does make them unnecessarily difficult to follow! (I have edited your last two comments here, accordingly.)

**Comment by jjgomezcadenas** [comment]
>@jjgomezcadenas Could you please prepend > to text that you are quoting? 

Like this? With pleasure. Sorry!

**Comment by paolafer** [comment]
I don't think that the algorithms are the same. In fact, corona **calls** barycenter. If we really want to unify them, we should use lm_radius = 0 and new_lm_radius = infinity, in the case of barycenter...

**Comment by jacg** [comment]
> Like this?

That's it. Thanks.

**Comment by jjgomezcadenas** [comment]
>I don't think that the algorithms are the same. In fact, corona calls barycenter. If we really want to unify them, we should use lm_radius = 0 and new_lm_radius = infinity, in the case of barycenter...

Sorry, what I meant to say was that one algorithm was an special case of the other. Corona searches local maxima and then calls a barycenter around them. What we call barycenter (and should have called global barycenter) simply calls a barycenter for a given set of SiPMs. In any case there was no special reason to make these separate algos. They can be easily configured by parameters and actually they already are, so unless we have a specific reason to change the current choices (other than aesthetics), I propose to move on.

**Comment by jjgomezcadenas** [comment]
I think we can close this for now
