### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#353]
In #349 we have been discussing how to proceed regarding version control. So far, we have agreed to commit to the repository `.yaml` files with fixed versions of each package. The open question is how to proceed when upgrading to a newer version. This is not urgent, as we are now keeping the versions in a stable configuration, but has to be addressed in the future. We would also like to add some tests, to ensure we are actually using those versions (and it is not silently upgrading during installation or setup).

**Comment by jacg** [comment]
What we really need is a mechanism for keeping the conda environment package versions in sync with the currently checked out commit!

A rough outline of the implementation could be

1. add a utility to `manage.sh` which updates the `ICX.Y` environment to the versions specified in the now-committed `.yaml` file.

2. add a git hook which invokes this on every checkout. This could make checkouts veeeery slow! (And rebasing a real drag!)

3. somehow deal with the absence of the `.yaml` file in the first 1000 commits in the repo.

**Comment by jjgomezcadenas** [comment]
sounds daunting! And I wonder whether the evil (slow checkouts, rebasing) outweighs the good!
(sorry about too much chatting, I am caught with other obligations and I cannot code, thus talk is the last resort...)

**Comment by jacg** [comment]
We need to find a balance between the pros and the cons. Without automatic syncing of the dependencies with the client code using them, we will keep on running into stuff such as #299. This wastes precious time and resources.

The question is, what can we provide without making other things become too costly?

It is not a question that we can answer today.

Perhaps the right compromise might be a big `RECONFIGURE EVERYTHING` button, which does stuff like

+ update the conda env to the correct dependency versions
+ recompile any Cython modules
+ download the correct database version
+ etc. (please edit this comment if you can think of anthing else that belongs on this list. In fact, we should probably make this list into a checklist in the first comment on this PR!)

**Comment by jacg** [comment]
I think that this is being addressed by #496.
