### ISSUE TITLE
Loading multiple DST and hits files

### ISSUE THREAD

**Issue by jerenner** [next-exp/IC#356]
For loading DSTs there are currently two functions, one (load_dst) to load a single DST and another (load_dsts) that loads several and concatenates them:

1. Should these functions be combined into 1 single function that handles both cases (single file or multiple files)?
2. Should a similar function be written to load hits from multiple files?  (Currently load_hits only handles 1 file)

**Comment by gonzaponte** [comment]
I think we can combine them. If we force the arguments `group` and `name` to be keyword arguments we can take an arbitrary number of files as positional arguments using the star syntax.

**Comment by jjgomezcadenas** [comment]
Is this issue solved then @gonzaponte? Can we close it?

**Comment by gonzaponte** [comment]
It is not *solved*, because we haven't discussed it. I am in favor of a single function handling both cases, but there isn't any other opinion here...
