### ISSUE TITLE
Compile-only option

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#361]
Can we include a compile cython components option to `manage.sh` that doesn't run the tests?

**Comment by gonzaponte** [comment]
Maybe it is not necessary since the compilation is done entirely by the command `python setup.py develop`.

**Comment by jacg** [comment]
At worst, you issue a command that compiles and tests, and then interrupt it once the compilation has finished.

Of course, an implementation of your idea is only 1 line long (but testing stuff in `manage.sh` is almost impossble to automate).

Anyway, I'm closing this. If you feel that it is useful, don't re-open this issue, just submit a PR with the implementation, which, an I said, shoud be one line long: the function already exists in `manage.sh`; you simply have to add it to the dispatcher. Hmm, you'll also need to add it to the command line completion helpers.
