### ISSUE TITLE
Assign merge commits to reviewer who approved PR

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#363]
We currently have a policy to assign merge commits to the main author of the commits in a PR. I propose that we switch to assigning the merge commit to the reviewer who approved the PR, with the approval comment included in the merge commit comment, along with the main comment introducing the PR.

[edit: We should also include the PR number in the commit message. Better still, in the title of the commit message. There may be plenty of background information on the code stored in the conversation of the PR, but, currently, finding the corresponding PR is difficult.]

In the case of single-commit PRs we do not have a separate merge commit, so there only the author would appear.

**Comment by gonzaponte** [comment]
I don't disagree, but can you elaborate on the logic behind it?

**Comment by jacg** [comment]
Review and approval of a PR are a significant part of the PR's history. Currently we note authorship in the commits themselves, but we have no record of the identity of the reviewer, except trawling through the PRs on GitHub, but there is no link between the commits that make up the PR in a local repo and the GitHub PR in which they were accepted.

The author is probably the primary source of wisdom about a piece of code. The reviewer is likely to be the second most informed person on that particular topic. It is useful information to have.

I can get a fair idea of the author of a piece of code with `magit-blame` in seconds. Identifying the reviewer currently takes a too much effort.

I would propose that the PR number should be included in the merge commit message too.

**Comment by gonzaponte** [comment]
Sounds good to me.

> I would propose that the PR number should be included in the merge commit message too.

Yes, I find that particularly useful.

**Comment by jjgomezcadenas** [comment]
I smell blood soon to be spilled here...

**Comment by jacg** [comment]
>> the PR number should be included in the merge commit message

> Yes, I find that particularly useful.

Yup, I think it's the most important part of the idea. Adding the URL of the PR in the message body could be good.

> I smell blood soon to be spilled here...

Oh yessss, the hounds shall be unleashed.

**Comment by jacg** [comment]
Do we agree to the following merge policy?

Mergers should use the PR number and title as the title of the merge commit. The merge commit comment should contain the most useful and informative combination of the PR's opening comment and the reviewer's acceptance comment.

If we stick to this policy then I have no strong opinion whether the merge commit should be assigned to the author or the reviewer who approved the PR.

**Comment by gonzaponte** [comment]
I do agree.

> Mergers should use the PR number and title as the title of the merge commit.

I want to emphasize that we (me particularly) should use more descriptive titles in our pull requests. Reviewers must demand a better title if it describes the PR poorly.

**Comment by jjgomezcadenas** [comment]
I sense the raise of new era of better men here. Watch out! Regula mortals may be scared by too much a liberal use of "must" and "should".

**Comment by jacg** [comment]
And there I was wondering what literary reference I had missied in *Regula*. Is this Regula some sort of god or daemon? Imagine my disappointment when I figured out she was just a typo!

**Comment by jjgomezcadenas** [comment]
What actual code you refer to?

**Comment by paolafer** [comment]
> And there I was wondering what literary reference I had missied in Regula. It this Regula some sort of god or daemon? Imagine my disappointment when I figured out she was just a typo!

Same for me, hahaha!

**Comment by jacg** [comment]
@jjgomezcadenas Now you've really lost me. In this thread I am not referring to any code at all. I am referring to your previous comment.

Are you sure you meant to post here?

**Comment by jjgomezcadenas** [comment]
Sorry, yes, I had not seen the typo! Of course I meant Regular mortals.

**Comment by jacg** [comment]
It seems that we are broadly agreed. Here is our new policy for commits that merge PRs into `next/icmaster`:

1. Start the merge commit *title* with 'PR #XYZ'.

2. Include the URL of the PR in the commit message.

3. Include as helpful as possible a combination of the introduction comment and approval comment in the commit message.

4. Set the approving reviewer as the author of the merge commit.

These are listed in decreasing order of importance. Forgetting the first one is unforgivable. Fewer digits will be amputated as punishment for forgetting to do the things lower down the list.

Unless I hear dissent before then, I will close this issue tomorrow morning.

Now, I wonder to what extent this can be automated ...

**Comment by jacg** [comment]
I hereby declare the policy set out in the previous comment to be the official IC merge-commit policy.

**Comment by gonzaponte** [comment]
This policy applies to multiple-commit PRs only, right?

**Comment by abotas** [comment]
There is no merge commit with single commit PRs, right?

So the policy can only apply to multiple-commit PRs

**Comment by gonzaponte** [comment]
Yes, that was my reasoning too, but should I reword the commit to include the PR number, for example?

**Comment by abotas** [comment]
I would guess yes, so they look consistent... but that's just me

**Comment by jacg** [comment]
Yes, this only applies to PRs with a merge-commit, which only exist for PRs with more than one commit.

Rewording to include the PR number would be good.

**Comment by jacg** [comment]
We have agreed to start merge commit titles with `PR #nnn`.

I propose that we save ourselves 3 precious characters by dropping the `PR ` and using just `#nnn`.

**Comment by jacg** [comment]
There's just one problem with using `#nnn` at the statr of the title: Git understands `#` at the beginning of a line as a comment.

Simple solution: put a space before it. This saves us only 2 rather than 3 characters. I'll take it.

**Comment by jacg** [comment]
I propose a further minor simplification to the merge commit tile policy (saving us another 2 precious characters!): drop the `<space>#` and just start the title with the digits of the PR number.

Please respond with the thumbs-up or thumbs-down emoticon in the GitHub interface. I'll consider the results of this referendum in a few days.

**Comment by jacg** [comment]
I hereby declare this referendum to have decided, with an overwhelming majority of 3-0, that henceforth PR merge commit titles shall start with the PR number (omitting the `<space>#` that we have been using so far).
