### ISSUE TITLE
We need to review PRs

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#377]
We have about 10 PRs opened and more are coming. We need to start reviewing and approving some of them, or we are gonna stale development. Ideas??

**Comment by abotas** [comment]
I have no ideas but I can help approve at least the ones I understand

**Comment by jjgomezcadenas** [comment]
Actually there is a PR from you still hanging... what is the status?

**Comment by abotas** [comment]
Yes! That is almost done-- as it has been for far too long-- I think I can make it all the way done by tomorrow.

**Comment by jjgomezcadenas** [comment]
Every one, PRs are accumulating again, we need reviewers to review and get them out of the way, before attacking the major refactoring coming in...

**Comment by jacg** [comment]
The likely consequence of having an unmerged PR before starting The Big Refactor, for PRs in general, is great pain and suffering for whoever is going to rebase the PR afterwards.

But please note that approval of #394 is a **hard prerequisite** for proceeding with The Big Refactor ... and given that travel arrangements and accommodation for The Big Refactor are being/have been arranged, not approving #394 in the next week is not an option!

**Everyone** should consider reading, understanding, thinking about and commenting on #394 to be a **top priority**. This PR has the hugest impact on **everybody**: you, yes that's **you** need to give it some serious attention **ASAP**.

**Comment by paolafer** [comment]
What does the Big Refactor address?

**Comment by jacg** [comment]
The Big Refactor will replace the old PMAPs interface with whatever is approved in #394.

**Comment by jacg** [comment]
... also, we need to make sure that @andLaing 's PR (#399) does not get neglected. It is important that we develop the habit of making new contributors' entries as smooth, painless and welcoming as possible.

**Comment by jjgomezcadenas** [comment]
Actually, my opinion is that we really must get as many PRs as possible out of the way before the big Refactor. Many of the PRs seem to be there just because people seem to suffer of the opposite illness I do. For me, as it is well known, the longer the PR lingers, the less your level of Karma. Instead, some of the PRs, like the one open by @bpalmeiro seem to carry on forever apparently to win Karma points. Let's clear them out. Also, I agree, let's try to accommodate @andLaing ASAP.

**Comment by gonzaponte** [comment]
> we really must get as many PRs as possible out of the way before the big Refactor.

That is true. However, take into account that the big refactor will consist of 4 PRs and only the 3rd one will be troublesome.

> apparently to win Karma points. 

There is no karma involved here.

**Comment by jjgomezcadenas** [comment]
Please, usual suspects, @gonzaponte, @abotas, @jmbenlloch, @paolafer, @bpalmeiro, review and get rid of open PRs and obsolete issues before TBR!

**Comment by jjgomezcadenas** [comment]
EVERYONE, the number of PRs is growing out of control. Please try to review them!

**Comment by jacg** [comment]
I think that this one has found new life in #513, so let's close it.
