### ISSUE TITLE
Masked channels

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#387]
During today's S&A meeting I've realized that we are not taking into account masked channels in the corona algorithm. They matter, because we ask the sensors within corona be more than a fixed number. If one of these sensors is masked, this number should decrease by 1 (this is how we had  corona implemented in art). I can take care of this, but I wanted to raise the issue, first, because this change implies using database information on xy_algorithm functions, and I don't know if IC ethics allows that...

**Comment by paolafer** [comment]
Maybe we could keep this information outside xy_algorithm, just changing the corona parameter nsipm in the place where the algorithm is called (HitCity, maybe?).

**Comment by gonzaponte** [comment]
>  this change implies using database information on xy_algorithm functions

The functions can take an extra argument with the masked sensors or something like that. I think we can and should avoid introducing the `database` dependence in `xy_algorithms`

**Comment by gonzaponte** [comment]
> Maybe we could keep this information outside xy_algorithm, just changing the corona parameter nsipm in the place where the algorithm is called (HitCity, maybe?).

I have just taken a look at the code and this seems a reasonable option. However, I don't see yet how are going to take this into account, because we don't know if a masked channel is around the signal region or not. And even if we know, we can't know whether it would have had signal or not.

**Comment by paolafer** [comment]
Right, you need to know which one is the hottest SiPM, to know its neighbours...

**Comment by gonzaponte** [comment]
Ok, I have seen the C++ implementation as well. I like your proposal. Are you going implement it?

**Comment by paolafer** [comment]
Yes, but I think that we *need* to make xy_algorithm dependent on database. Is that ok?

**Comment by gonzaponte** [comment]
I don't see the need for that. As you mentioned earlier...

> we could keep this information outside xy_algorithm, just changing the corona parameter nsipm in the place where the algorithm is called

**Comment by jjgomezcadenas** [comment]
This is not a problem, we use the data base all the time and have a local copy of the data base at our disposal.

**Comment by gonzaponte** [comment]
*Conceptually*, `corona` does not need to know about the database. The function is designed to be "abstract" in the way that it takes x-y positions and charges and produces an invariant result. This encapsulation makes our life easy in many ways (testing is a good example of that). If you need to handle special cases, do it separately and pass "pure" information to your algorithm. If we begin to introduce special cases within the function, it loses its generality. On top of that, the database is a mutable structure and should not be used in something as "pure" as a reconstruction algorithm, I think.

**Comment by paolafer** [comment]
I mentioned that, before realizing what you pointed out, that one needs to know the hottest SiPM, in order to check if any of its neighbours is masked. But this piece of information is accessed only inside the corona algorithm... This is why I think that we cannot avoid calling the database from inside the algorithm. Am I missing something?

**Comment by gonzaponte** [comment]
Do you need to do that for each iteration? In any case, I think it can be done by passing the list of masked sensors to `corona`. There is a function `get_nearby_sipm_inds` that select those sensors that are nearby. It can also look for the masked ones if we have them.

**Comment by paolafer** [comment]
Ok, if you prefer this way.

**Comment by jacg** [comment]
I feel that these words of wisdom need to be emphasized (though "abstract"  and *encapsulation* should really be *pure* and *purity* or *referentially transparent* and *referential transparency*, so I have taken the liberty of editing the text):

> *Conceptually*, `corona` does not need to know about the database. The function is designed to be *referentially transparent* in the way that it takes x-y positions and charges and produces an invariant result. This *purity* makes our life easy in many ways (testing is a good example of that). If you need to handle special cases, do it separately and pass "pure" information to your algorithm. If we begin to introduce special cases within the function, it loses its generality.

... and its simplicity, comprehensibility, debugability, testabilitiy and many other valuable -ities.

Listen to this man! (For he understands the perils of the IO monad!)

And this has nothing to do with `corona` specifically: In general you should aim to make components as stateless, pure and referentially transparent as possible ... good things come of it, and you set yourself up for pain if you do otherwise.

Avoid side-effects as much as you can. Separate stateful components from referentially transparent components. **Do not pollute referentially transparent components with side-effects and state**, instead combine them by

+ passing the results of state-dependent components into pure ones
+ passing the results of pure components into side-effectful ones. 

Strive for *composability* of *orthogonal* components.

**Comment by jjgomezcadenas** [comment]
Jesus Almighty! How may karma points has @gonzaponte won on this one???

**Comment by paolafer** [comment]
Can I have at least one micropoint for having asked ;-)? So I can start the rising from ῞Αιδης where I lie...

**Comment by jjgomezcadenas** [comment]
This is a lovely conversation, but are we done here, @paolafer, @gonzaponte, @jacg ?

**Comment by jacg** [comment]
Besides the general advice not to pollute pure code with side-effects, I don't think I have anything specific to contribute to this one.

**Comment by gonzaponte** [comment]
At some point, we will have a PR that closes this by modifying corona. I guess this is @paolafer's work 🙂

**Comment by paolafer** [comment]
Yes, it's in my list!

**Comment by gonzaponte** [comment]
Closed via #430.
