### ISSUE TITLE
Possible bug in voxelize_hits

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#389]
After a careful comparison of our codes and results using paolina functions, @jerenner and myself realized that, using different versions of those functions, the results change substantially.
In particular, while I'm using the current master, Josh is using a master at commit 07e9f9a21bc97bdedfd90d66a89d713a301ab99a.
In particular, the energy distribution of the blobs is very different, the selection of events being the same.
As an example, I attach one event of data, where the new master reconstructs two blobs with really small energy and the older version reconstructs two blobs with similar and quite high energy. I attach a file with the reconstructed hits and two files with the list of voxels and blobs given by the old (bug_josh) and the current (bug_new) versions of the master.
[possible_bug.zip](https://github.com/nextic/IC/files/1446656/possible_bug.zip)

Whether the correct result is the one with the new or with the old version, is not clear to me. The only difference is in the way we define the boundaries of the voxels, which shouldn't introduce such a big difference. If it does, we should study why the old (and incorrect, in the sense that it didn't do what we wanted) version gives better results, since it may open a window to improving the code.

**Comment by paolafer** [comment]
After a bit more of playing with voxelization, I may have a possible explanation why the two versions of the algorithm perform differently, actually why the "wrong" version (let's call it 'old') performs better than the "right" ('new') one. @jacg, please, shout out loud if I misunderstood some part of your code.

Let me remind you the difference between the two versions:

old: the size of the voxels, although given to the algorithm by the user as a fixed parameter, are slightly different event by event. This happens because the axis ranges of the 3D histogram used for the voxelization are not calculated explicitely, but they're set automatically by the np.histogramdd() function, given the number of bins. Therefore, depending on the positions of the most outer hits, the ranges vary, thus the bin size varies as well.

new: the size of the voxels are fixed by parameter. The ranges of the histogram axes are calculated accordingly. Therefore, although the ranges depend also on the positions of the hits, they do it in a more rigid way. A consequence of this fact is that the most external hits may fall inside a voxel whose border is far from the hit, something like this:

           |       x |          | ...
       

instead of:
            
           | x       |          | ...


The second voxelization allows to make a mor accurate estimation of the extremes of a track, and I think that this is the reason why the 'old' algorithm works better in blob reconstruction.

This shouldn't make a big difference, if the voxel size is small, but since we're using 15 mm cubic voxels, I suspect that it does.

If this explanation is true, we could live with a variable size of the voxels event by event, provided we use the actual size instead of the fixed one to calculate vicinities in the algorithm.

I'm willing to try this approach and see if it improves the tracking.

**Comment by jacg** [comment]
> I may have a possible explanation why the two versions of the algorithm perform differently, actually why the "wrong" version (let's call it 'old') performs better than the "right" ('new') one.

This is exactly the point I was trying to get across in my emails of `2017-10-07 12:48` and `2017-10-07 13:39`.

Apparently I failed. Sorry.

**Comment by paolafer** [comment]
Yes, but I'm a bit slow, you have to forgive me!!! I didn't realize that this voxel size thing had such a big impact in blob distribution, so I just catalogued the issue as 'solved' in my head at that time, until I bumped into real data with some problems and I had to re-discover it again.

**Comment by paolafer** [comment]
I go back to this issue with two plots to illustrate the behaviour of a fixed vs variable voxelization.
[SigVsBckg_variable_voxels.pdf](https://github.com/nextic/IC/files/1501517/SigVsBckg_variable_voxels.pdf)
[SigVsBckg_fixed_voxels.pdf](https://github.com/nextic/IC/files/1501519/SigVsBckg_fixed_voxels.pdf)

I have used a 15mm voxelization and a radius of 21 mm. For the first plot, I have used the code in PR #396, meaning a voxelization with variable size, event by event. For the second plot I have used the current master code, meaning a fixed size for voxels. I have tried three different ways of building the blobs:
1. voxel_based blobs: the traditional one, where the energy of the **voxels** whose centres fall within a sphere of radius R (centred in each one of the extremes) is summed.
2. hit-based blobs: the blobs are built with the energy of the **hits** that fall within the above described sphere.
3. bary_hit-based blobs. As 2., but the centre of the sphere is now the barycenter of the positions of the hits inside the voxels identified as extremes.

The variable voxel size gives a better discrimination than the fixed one.

**Comment by jacg** [comment]
Interesting how the relative efficiencies of the three approaches are re-ordered when going from fixed- to variable-sized voxels.

I can see why the barycentre version might do better than the others for fixed-size, but I'm puzzled by it being overtaken by the others when going to variable-size.

**Comment by paolafer** [comment]
Me, too, in fact now I'm rerunning the analysis, because I've found a mistake in the way I was selecting the hits inside the extreme voxels: I was requiring that the distance between the centre of the voxel and the hit be lower then the voxel size, for each dimensions, while it should be lower than half the voxel size. I'll post the new results soon.

**Comment by jacg** [comment]
... which would be correct for spherical voxels, but these are cuboidal!

**Comment by paolafer** [comment]
I've noticed a problem with variable-size voxels: when I look for the hits inside the extreme (with the condition mentioned above), I often find none. I had a look closer to a specific event, and it happens when only one hit belong to the voxel, and it is exactly on the boundary. Could there be a problem of rounding there? I'm requiring <=, but the problem stays there.

**Comment by jacg** [comment]
7277c078 attempts to deal with exactly this problem. Try increasing the `eps` which appears therein, and see whether that solves your problem.

**Comment by paolafer** [comment]
This commit deals with fixed-size voxels, while I find this problem using the variable-size code, where the actual range of the histogram is dealt with internally by histogramdd, if I understand it correctly.

**Comment by jacg** [comment]
Ah, yes, I had it backwards, sorry.

Try [this branch](https://github.com/jacg/IC/tree/switchable-voxel-size-strictness) where I

+ add an option for fixed or variable voxel size
+ apply the same margin of error trick to both.

This hopefully

+ makes it easier for you to compare the two approaches
+ avoids the problem you reported

**Comment by paolafer** [comment]
I'm looking at the code, but I'm afraid I don't understand how this code deals with fixed or variable voxel size. Anyway, in both cases voxels are built with a size equal to the one that is given as argument of voxelize_hits, while in the case of variable voxel size it should be the actual one.

**Comment by jacg** [comment]
> in both cases voxels are built with a size equal to the one that is given as argument of voxelize_hits

I find that very hard to believe: as it stands the code passes all tests; change the default value of the `strict_voxel_size` parameter from `True` to `False` and `test_voxelize_hits_repsects_voxel_dimensions` fails. This directly contradicts your claim, as I understand it.

In addition to having performed this check before committing, pushing and commenting, I repeated it again just now, so I'm fairly confident that I haven't missed anything.

**Comment by paolafer** [comment]
Voxels are built explicitly with the voxel size that has been passed as an argument:
`return [Voxel(cx[x], cy[y], cz[z], E[x,y,z], voxel_dimensions) for (x,y,z) in np.stack(nz).T]`
Maybe they have a different size, but their property size is being set erroneously?

**Comment by jacg** [comment]
Yes indeed.

You push the test that shows this up, I'll push the fix.

**Comment by paolafer** [comment]
I pushed it in [this branch](https://github.com/paolafer/IC/tree/switchable-voxel-size-strictness). I modified the make_track_graph method, which doesn't need to receive the voxel size anymore.

**Comment by jacg** [comment]
Have a look to see whether the solution in my branch does the trick for you.

I split your commit into two, because there were two completely unrelated bits of work in there:

1. removing the `voxel_dimensions` parameter from `make_track_graphs`
2. adding a completely new test

I also changed the test, as simply requiring `!=` admits any old rubbish as a correct solution. (And that includes my first failed attempt at fixing it.)

The test is still not strict enough: we need to think about a reasonable lower bound. But I have other pressing things to deal with right now.

**Comment by jacg** [comment]
Our hypothesis hard profile finds a problem with this (as I was half-expecting).

I'm about to go offline. Not sure when I'll have time to take it further.

**Comment by paolafer** [comment]
Errata corrige: this is not a correct example, the following set of voxels actually works fine. I'll try to find another one.

No problem, I'll keep posting my findings, have a look whenever you can!
First thing, I realized that something weird happens when events are made by a bunch of hits that fill only few voxels. For instance, the following set of hits:

 38.42050696   33.12655555  298.2       
 44.13063441   32.52593075  300.2       
 43.38564304   13.10577117  300.2     
 22.43202033   26.26994429  300.2
  42.64044946   27.03150613  302.2 
  44.03787451   47.45019986  302.2  
  22.16901317   26.24873783  302.2  
  38.01676398   27.36642243  304.2 
  53.39873647   36.28763318  304.2 
  44.77132027   32.3139153   306.2

, when voxelized with voxel size = 15 mm, gives 10 tracks (!!!) of 1 voxel each. 
I will go deeper into that tomorrow.

**Comment by paolafer** [comment]
I've tried to increase the margin from 10e-12 to 10e-06, and the number of events where no hits are found in the extreme voxel is reduced, but is not zero. Is there a way to know exactly what this margin should be? Shouldn't it depend on the precision? And can we set the precision to a value we want?

**Comment by jjgomezcadenas** [comment]
Is this issue understood, @paolafer ?

**Comment by jacg** [comment]
Just like the others, it requires me to find some time to make some progress on it.

**Comment by paolafer** [comment]
I believe that this issue has been solved with PR #603, therefore I close it.
