### ISSUE TITLE
Test failing because of updated database

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#390]
We have a test failing because of a recently masked sensor in the database. @jacg is it ok with you if we push a quick temporary fix (`mark.skip` the test) and keep it in our TODO list for a while? We don't have time to be spent here now and we don't want continuous fails of travis builds. Besides, the test is not very relevant as that part of the code is very stable.

If so, can it be pushed directly (without a PR involved)?

**Comment by jacg** [comment]
@everybody-in-IC It's course week, so assume long delays in me reading, let alone answering, what you write. Best assume that I'm offline until the weekend.

@gonzaponte After 3 seconds of consideration, what you propose seems reasonable.

**Comment by jjgomezcadenas** [comment]
@gonzaponte can this issue be closed?

**Comment by gonzaponte** [comment]
Yes, closed by #392.
