### ISSUE TITLE
Magit installation doesn't work with Mac

### ISSUE THREAD

**Issue by andLaing** [next-exp/IC#401]
Using the init.el script provided in nextic/docs I get the following errors.
```
fatal: destination path 'el-get' already exists and is not an empty directory.
```

I can't find where it is installed (it's not in .emacs.d/)

Additionally, I get the errors:
```
Warning (el-get): Your Emacs doesn't support HTTPS (TLS).
Warning (initialization): An error occurred while loading ‘/Users/laingAndrew/.emacs.d/init.el’:

error: Couldn’t clone el-get from the Git repository: https://github.com/dimitri/el-get.git

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Mac and aquamacs info:

Mac OSX 10.12.6

Aquamacs 3.3  GNU Emacs 25.1.1

Any ideas? José María and I are not having any success solving the problem so far.

**Comment by jacg** [comment]
Try the new `init.el`provided in #402.

**Comment by andLaing** [comment]
Tried.

It seemed to have worked but then when I restarted aquamacs it now doesn't seem to see the init file and opens a normal emacs window where magit commands are not recognised.

**Comment by jacg** [comment]
Just to be sure: you are putting this init file in an empty directory called `.emacs.d`?

**Comment by andLaing** [comment]
Yes, but on my Mac it isn't empty, there's a SessionDesktop.el file. I've just tried removing this but to no change.

**Comment by jacg** [comment]
Hmm, Aquamacs does all sorts of weird things to Emacs, but would I hope it wouldn't break anything at this level.

Let's try this:

1. `mkdir ~/magit-install-test`
2. `cd ~/magit-install-test`
3. `mkdir .emacs.d`
4. `cd .emacs.d`
5. `curl https://raw.githubusercontent.com/jacg/IC/docs.emacs-init/doc/init.el -o init.el`
6. `cd`
7. `HOME=~/magit-install-test emacs &`

... assuming that `emacs` opens your AquaMacs ...

If that seems to install correctly, then exit AquaMacs and restart it again with `HOME=~/magit-install-test emacs &`

If that still doesn't work, could you try it with this

    https://emacsformacosx.com/

instead of AquaMacs?

**Comment by jacg** [comment]
... to be on the safe side, change out of the new `.emacs.d` directory before starting emacs, as per the edit in the comment above.

**Comment by andLaing** [comment]
Same randomness. Works the first time then doesn't after reset.

I'll have a look at the other version of emacs.

**Comment by andLaing** [comment]
Hi

I managed to get round to installing the alternate version of emacs as you recommended.

The good news is that I don't get the same error, the bad that there's still an error. Opening with ```--debug-init``` I get the following error:
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "diminish")
  require(diminish)
  eval-buffer(#<buffer  *load*> nil "/Users/laingAndrew/.emacs.d/init.el" nil t)  ; Reading at buffer position 324
  load-with-code-conversion("/Users/laingAndrew/.emacs.d/init.el" "/Users/laingAndrew/.emacs.d/init.el" t t)
  load("/Users/laingAndrew/.emacs.d/init" t t)
  #[0 "\205\266	\306=\203\307\310Q\202?	\311=\204\307\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210\324=\203e\326\327\330\307\331Q!\"\325\324\211#\210\324=\203d\210\203\247\332!\333\232\203\247\334!\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337\"\203\243\340\341#\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()
```

**Comment by jacg** [comment]
Diminish isn't actually used anywhere in the file (I think), so you can remove the `(require 'diminish)` line from `init.el' ... which should make that particular problem go away.

**Comment by andLaing** [comment]
Removing the ```(require 'diminish)``` line from the init.el worked. Loads without error and quitting and relaunching still gives me access to magit commands.

Cheers.
