### ISSUE TITLE
New DST for diffusion analysis

### ISSUE THREAD

**Issue by Aretno** [next-exp/IC#404]
Hi everybody, 

as I told you in the software workshop we had two weeks ago I am currently creating my own DSTs for the diffusion analysis, which is a big no-no. Therefore, I need to make some city (I believe at least one) in order to officialize everything.

At the moment, I am generating three DSTs, each one for a different study: 

First one that has mean XYZE and the Zrms, this is to be implemented in the coming days (i believe it has been done while writing this) by expanding dorothea, therefore I am covered on that side.

Another one that has mean XYZE of the full event and adds an entry for each slice, adding the relative position of the time slice (first slice will be 0, next will be 1, etc.) and the energy of each slice:

| X      | Y      | Z      | E      | SlicePos | SliceE   |
|--------|--------|--------|--------|----------|----------|
| x_mean | y_mean | z_mean | e_mean | 0        | slice0_e |
| x_mean | y_mean | z_mean | e_mean | 1        | slice1_e |

@gonzaponte told me for this one it may be possible to tune Penthesilea config parameters to end with this result but I dunno which would be the necessary parameters.

Finally, I am using a DST that has mean XYZE of the event (again) and the integrated charge of each SiPM plus its ID:

| X      | Y      | Z      | E      | SiPM ID | SiPM Q |
|--------|--------|--------|--------|---------|--------|
| x_mean | y_mean | z_mean | e_mean | 1002    | q_1002 |
| x_mean | y_mean | z_mean | e_mean | 1003    | q_1003 |

This one is also used for generating the RESET SiPM probability maps so it may be rather necessary. I don't know if this could be added into Penthesilea in some way (using an algo that makes hits = SiPMs, with a rebinning big enough to contain all the event), making something Dorothea alike, or what do you believe will be the best approach, whatever the software masters believe will be fine by me.

Many many thanks!

**Comment by gonzaponte** [comment]
> i believe it has been done while writing this

Yes, this has already been done in #381.

> one that has mean XYZE of the full event and adds an entry for each slice,

If you need the xyze ***of each slice***, we can achieve this by simply adding a "hit number" column to `Penthesilea`'s output. After that, you will only need to run it with the barycenter configuration (so there is only 1 hit per slice).

Otherwise, we might need a new city. However, you could first try to use the `groupby` method of `pandas.DataFrame` which can (as the name suggests) group rows by some property and latter apply operations to each sub-`DataFrame` to perform selections and other stuff.

> a DST that has mean XYZE of the event (again) and the integrated charge of each SiPM plus its ID

For the last proposal, I think we definitely need a city.

**Comment by jahernando** [comment]
I have the impression, Ander, that your DSTs for PSFs are better covered by Penthesilea's hits. In the case we can make a hit for each individual SiPMs, which I think it will be good thing to do. Several studies can start from these Penthesilea's hits. Can you check with Josh?

**Comment by Aretno** [comment]
> Yes, this has already been done in #381.

Great, cool.

> If you need the xyze of each slice, we can achieve this by simply adding a "hit number" column to Penthesilea's output. After that, you will only need to run it with the barycenter configuration (so there is only 1 hit per slice).

Well, I do not need the xyze of each slice, only the e and the xyz of the full event, but I guess I could do a barycenter of those slices. However if I go that way I probably won't be able to cut easily on the events (or at least not as easily as the typical DST). Still I'll need to look into that `groupby` because it may be what I would need for the cuts.

> I have the impression, Ander, that your DSTs for PSFs are better covered by Penthesilea's hits. In the case we can make a hit for each individual SiPMs, which I think it will be good thing to do. Several studies can start from these Penthesilea's hits. Can you check with Josh?

I just spoke with him, he believes that if the search radius is small enough (<10 mm) it should work, I'll try and check if that works then. Still, I don't know if we rather have a city or run with this particular configuration.

**Comment by Aretno** [comment]
I have tried and successfully (kind of) obtained the DSTs that could be obtained through Penthesilea. However for the longitudinal difusión, where I need the cathode energy each slice (1 mus slices) there are cases where the SiPM don't see light, therefore no XY position is reconstructed and the barycenter of the integrated charge differs from the barycenter of the slice's position. However is a small effect so I may live with that if I cannot sort it out by tuning Penthesilea's parameters.

Once I have these penthesilea DSTs I wonder if it is allowed to add information to them. Since they don't have the mean position of the event, for example, I prepared a code to add that column (using groupby) into the penthesilea output DST so... is this a big no-no or this can be done? I don't plan to save this DST, is only done locally on the notebook for making the selections and filters easier.

**Comment by jjgomezcadenas** [comment]
>I have tried and successfully (kind of) obtained the DSTs that could be obtained through Penthesilea. 

Not clear to me what you mean. Penthesilea writes a hits DST. Enough for you?

>Once I have these penthesilea DSTs I wonder if it is allowed to add information to them.

Yes you are!

>Since they don't have the mean position of the event, for example, I prepared a code to add that column (using groupby) into the penthesilea output DST so... is this a big no-no or this can be done?

It can be done, of course, and the question is whether one could already write this info at Penthesilea level, which I think is both easy and OK. Any opinions, from @gonzaponte et al?

>I don't plan to save this DST, is only done locally on the notebook for making the selections and filters easier.

At nb level you are, indeed authorised to do whatever you need to do for your analysis, but I think we can and must provide a DST that fits your needs.

Good job!

**Comment by Aretno** [comment]
> Not clear to me what you mean. Penthesilea writes a hits DST. Enough for you?

Yes, it seems to be more or less enough; with an adequate Penthesilea configuration I can obtain the two DSTs I needed. The only thing I would need to add is the XY mean position of the event and the position of a slice within the event (first slice = position 0, second = position 1, etc.). I have figured how to add both of them to the DST "a posteriori" but if they can be added to the standard Penthesilea DST, that would work great. However, I have my doubts regarding the slice position, it seems really specific for the few runs I am looking at. Besides from that I think everything will be kind of ok to start thinking of the dreaded PR.

**Comment by jjgomezcadenas** [comment]
OK, probably we can add the XY mean position of the event (this is just the overall baricenter, right?) and let you add the position of the slice on the fly. And yes, you will need to prepare PR...

**Comment by jjgomezcadenas** [comment]
After discussion we agree that:

1. @Aretno  (with the help of @gonzaponte) will modify the existing Hit DST to add a couple of variables of use for diffusion analysis. 

2. @Aretno will commit his analysis code to ICARO.

Agreed? Can we close this issue?

**Comment by Aretno** [comment]
Agreed, I'll close the issue.

**Comment by Aretno** [comment]
I'm reopening this (or should I open another issue?) because I almost have the PR ready but I'm having some trouble with some test's fixtures, concretely with `TlMC_hits` and `TlMC_hits_skipping_NN`. This causes that some tests fail (`test_load_hits_load_events`, `test_load_hits_double_ratio_e_q_equals_one` and `test_load_hits_double_ratio_e_q_equals_one_skipping_NN`). This is due because the file (`dst_NEXT_v1_00_05_Tl_ACTIVE_100_0_7bar_DST_10.h5`) that is loaded was created at some point without the event XY position that I want to add so the loading functions fail as it does not find the added fields in the DST. 

So... here I don't really know what to do. Shall I manually create the DST with the associated pmap file? It states that the DST was created as: `# Input file was produced to contain exactly 15 S1 and 50 S2.`; if that is the case I do not know how to create such a DST.

**Comment by jjgomezcadenas** [comment]
Well, we have hit the classical problem of schema evolution... we want to change our DST and all the tests (plus all the reconstruction code written so far) assumes the old format DST. 

One possibility is to add to your code a flag that decides wether you should. read old or new format. This makes your code backwards compatible, which I suspect is a must. In particular, if the default is "old format" the test will pass as they are. Then you can create a new DST with a few events, and add new tests with the flag at "new format", to check that everything is OK.

Rather than "old format" and "new format" one can find better names, such as "DST.v1.0", "DST.v.20". Ideally, the code can be smarter than that and "Know" from the file time stamp which version was used to create the file, but I think one could make do with a simpler fix (e.g, the famous flag 
DST_type = "DSTv1.0", etc.).

@jacg, @gonzaponte, any better ideas?

**Comment by jacg** [comment]
I'm sorry, I have reached my absolute limit of things that my brain can juggle. If I let this question penetrate my consciousness I will simply grind to a halt and not make progress on *anything*.

I'll think about this in January.

**Comment by jjgomezcadenas** [comment]
well then, if nobody says the contrary, I propose to try the flag fix for the time being, as a way to let @Aretno progress. Ask for help to @jmbenlloch or @abotas if you need a hand with the coding.

**Comment by gonzaponte** [comment]
> `# Input file was produced to contain exactly 15 S1 and 50 S2.`

Ignore it, I am quite sure the comment is there by accident. We have a long history of misleading comments. This one is mine, but it has been copied to other places where it does not belong.

The best solution would be to regenerate the file with your new columns. I think @paolafer produced that one. Let's see if she remembers which config was used and the original input file (which should be traceable by all the tags in the name).

Following from that...
***we must keep the input files that produce the test files and the configuration used. Otherwise, we'll find ourselves in this scenario over and over again.***


If we can't manage to regenerate the file I would generate a new one and fix the tests. It is more work and more tedious, but safer.

**Comment by Aretno** [comment]
There is a pmap file with practically identical name, that may be the one but yes, let's wait to Paola confirmation. In any case the flag should be added and we could use that file to test it as JJ suggests. I'll implement it. 

Thanks everybody, I'll leave the issue open till I submit the PR, in case additional problems arise.

**Comment by jacg** [comment]
> we must keep the input files that produce the test files and the configuration used. Otherwise, we'll find ourselves in this scenario over and over again.

And we must keep all this in version control, for which we need LFS or some alternative. Yes, I know that it's on its way, I just want to make sure that we all appreciate how important LFS is to us.

**Comment by paolafer** [comment]
Mmm, I'm not sure I know which file you're talking about. I'm pretty sure I never produced a DST file... Maybe we can talk directly on Skype tomorrow, @Aretno or @gonzaponte.

**Comment by Aretno** [comment]
Finally I managed to avoid using flags by using the getattr function so a default value of -1000 is set in case the hDST are older than this new hDST structure, I'll close now the issue and we can have further discussion on the PR (#415).
