### ISSUE TITLE
A (minor) refactoring of cities?

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#409]
While waiting for the BIG CITY REFACTOR (rumor has this refactoring will shake the Earth and nothing will ever be the same) I would like to propose yet another small city refactor (SCR hereafter).

Here is the logic. 

A city can be viewed as a machine that transforms a set of data into another. It needs to read the input data, process it even by event and eventually write the transformed data. The process involves an event loop which is nested inside a file loop, and the definition of a number of writers to save output data.

Consider first the case of Dorothea (Dotty) and Penthesilea (Patty). Bot cities read PMAPS (and thus can reuse the file and event loop). PMAPS can be served, through an abstract function to both cities and the result (a KrDST in the case of Dotty, a Hit DST in the case of Patty) can be written to disk. This is a case where (for the time being) no more refactoring is needed, as anyone can check by noticing that Patty and Dotty contain very little code. This is because they can reuse file loop, event loop and even filters (one can filter PMAPS before serving to the cities). In fact, the SCR would add a bit of code to Dotty and Patty, removing it from the base, since the code to select KDST or HitDST is too city-specific to be in the base. 

But this is not the purpose of the SCR. The reason why it may be interesting is as follows.

Consider now Irene. This is a city that needs to perform a large number of actions.
1. Read Raw Data (we need a different event loop that the one used by Dotty and Patty, since the input data is different, file loop is the same). 
2. Deconvolute RawData producing a new type of object (Corrected Data). Notice that we have a (largely unmaintained) city, called Isidora, that simply produced corrected waveforms and writes them. 
3. Produce calibrated sensor data. But our new city, sipmpdf (yes, the name is as ugly as it gets) just writes some of this calibrated sensor data to disk.
4. Compute PMAPS (which needs all the above) .
5. Finally write PMAPS.

The point is that we cannot treat the 3 cities (Irene, Isidora and sipmpdf) as we treat Dotty and Patty with a common event loop, because in this case each city wants to write a different data object and does not need to compute all the rest. Isidora does not need calibrated sensors, sipmpdf does not need PMAPS. Irene needs everything to compute PMAPS.

But, as thing stands today, we are triplicating the event loop (Isidora, Irene, sipmpdf), and in fact triplicating the number of cities. We could make do with a single city (Irene), by simply adding control cards which specify how far is Irene to go (one can stop at deconvolution, sensor calibration or go all the way to PMAPS), and what data must be written (one can write deconvoluted waveforms and/or calibrated data and/or PMAPS).

In practice, the proposed SCR would add a bit more of boiler plate to Irene, but it would allow to simplify the city structure, removing two cities that are largely duplications.

Finally, I would like to split base_cities.py into two or more modules. One could be city.py that contains all the code of the mega-base-class City, and the other would import that module to define the derived class (and would be called base_cities.py). The purpose of the split is to reduce the size of the current base_cities.py, sending city.py, which is a quite defined piece of code, to its own module. 

Please comment, in particular @jacg.

**Comment by jacg** [comment]
> as thing stands today, we are triplicating the event loop (Isidora, Irene, sipmpdf), and in fact triplicating the number of cities.

All these sorts of things are naturally solved by the dataflow paradigm proposed in #410.

**Comment by jacg** [comment]
> Finally, I would like to split base_cities.py into two or more modules. One could be city.py that contains all the code of the mega-base-class City, 

I want to *get rid of* the mega-base-class City, so I'm very reluctant to do any work on maintaining it.

In short, I want go skip this completely, and just get it done in #410.

**Comment by jjgomezcadenas** [comment]
OK, the crucial issue now is how long do you think this will take?

**Comment by jacg** [comment]
He-heh ... I have been around long enough to know that it is foolish to predict how long a significant piece of software work will take!

However, you and me with peras, I reckon we would knock it off in a week unless there are major surprises. Without peras ... 3 months.

**Comment by jacg** [comment]
Given that liquification *has* happened (even though it has not been merged yet) can we close this one?

**Comment by jjgomezcadenas** [comment]
yes
