### ISSUE TITLE
Making the cities invisible

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#410]
The cities (as is pointed out in #409) are machines which transform streams of data, typically performing operations event-by-event.

There are many problems with the current structure of the cities, which I will briefly summarize with two points

+ The structure is too difficult to understand
+ Code reuse is sub-optimal and difficult

I am using this issue to state publicly and officially what I have been hinting at and discussing with some individuals: I want to refactor the cities in order to express them as a *dataflow network*.

I have drawn an ascii-art [graph of the cities dataflow network](https://github.com/jacg/IC/blob/docs.city-graphs/doc/gity-graphs.txt) (I haven't had the time to make anything prettier) for your enjoyment.

In this paradigm, a city will be expressed simply by specifying the topology in which reusable components should be plugged together in order to fom a graph. As the comments at the top of the linked file above suggest, we could come up with an arbitrarily convenient DSL for expressing such topologies.

There are many technical foundations on which such dataflow networks might be expressed. I have done a search of the current art, and many candidates present themselves, but everything that I have found so far suffers from at least one of the following problems

+ It's too strongly coupled to one particlular computational engine
+ It's too complex
+ It's too verbose
+ It's not clear how to make it fit into IC without too much work
+ etc.

Therefore I propose that we start looking at how IC cities might be re-cast in this paradigm using [this small dataflow framework](https://github.com/jacg/IC/tree/dataflow/invisible_cities/dataflow). It's merits in this context are

+ It is simple to understand
+ It is simple to use
+ It will be easy to adapt to our needs
+ It is a pure-Python implementation (using native Python coroutines) which has no external dependencies

Please read the test suite which serves as a user-manual.

If we find that we can express the cities in this framework, it should be easy to translate them from this framework to third party dataflow packages, if we decide that a suitable wheel already exists and we do not wish to re-invent our own.

#409 proposes making a small refactoring of the cities. I am very reluctant to spend any effort on this, given that I want to get on with rewriting the cities in the dataflow paradigm as soon as I find some spare time (and I generally want to avoid the nausea that overwhelms we whenever I open a cities source file and contemplate changing something in it). In this context, unless #409 provides a stepping stone which makes this work easier, I would simply go straight to investing the effort into the dataflow paradigm.

**Comment by jjgomezcadenas** [comment]
While I agree with the need of a large refactoring and also agree with the technology proposed, I believe we must be realistic. This is a major refactoring and will take some time. Meanwhile I see no harm in improving what we have.

**Comment by jjgomezcadenas** [comment]
Shall we keep the discussion in a single thread?

**Comment by jacg** [comment]
I would like to keep the discussion of how and when we move to dataflow in this issue. Any discussion of an intermediate refactor of the cities does not belong here, but in #409.

**Comment by jacg** [comment]
The refactoring has been done (#435) and approved, but is awaiting merging in an upcoming sprint (#478). As such, this issue can be closed.
