### ISSUE TITLE
Plan for the sprint week

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#414]
Two people from Harvard (Justo and Corey) are coming to the spring week in January and they will need a full tutorial. In addition, I think that many people at IFIC could benefit from a refreshed tutorial on IC procedures and standards. 

Then we need to define our priorities and discuss how to proceed. What do we want to do, how, which organisation...

I see several hot topics coming:

1) City flows (@jacg, @jjgomezcadenas, @gonzaponte, @jmbenlloch at the very least)
2) DNNs integration (@jerenner, Mariya --I don't have her ID yet), + US people (@abotas will probably be in Houston).
3) RESET (@Aretno, @jmbenlloch). 
4) Productions in IC (@jahernando, @jmbenlloch, needs the advise of @jacg)
5) Migration to gitlab (local server), LFS? (Jose Vicente, needs advise from @jacg)
6) Code optimisation (out phase Cython, NP + nUMBA?)

and probably a long etc. Also in the list was graphics, but there is so much stuff going on that I doubt that we have the time for them. 

The assumption is that the week runs from 8 to 12, but I wander if @jacg could have a few days more, in particular if we want to give it a try to the City flows.

**Comment by jacg** [comment]
**If** the cities are going to be rewritten as dataflows, then I would be **really** keen on getting this done **before** anyone new is introduced to IC. Showing people the old stuff which is 

1. horrible
2. about to disappear and be replaced with something completely different

seems so wrong!

I am going to do everything humanly possible to try to do this, but this week I have to fix a number of long-standing problems that I have had in the course I am going to give next week. This means that I essentially have no time for IC until December 18.

As for the general plan for the sprint ... the point of sprints is to make progress. This means that people have to be able to concentrate full-time on whatever it is that they are working on. I worry that trying to cover too many topics will spread the person-power too thinly and no progress will be made on anything much.

**Comment by jacg** [comment]
**Before** migrating to GitLab it is **absolutely essential** to verify that we can reproduce our automated testing setup in GitLab CI pipelines. The procedure would be something like:

1. Create a `gitlab-migration` branch
2. push it to `master` on GitLab
3. remove Travis from it
4. configure CI pipelines
5. try pushing things and observing it in action ... and react accordingly.

IIRC, when I tried this a few months ago, looking at the CI output via its web interface was a lot more painful than in Travis ... to the extent of being a blocker. As GitLab is being actively developed, maybe this is no longer a problem.

**Comment by coreyjadams** [comment]
Thanks for starting this discussion for this week - I am looking forward to it.  I have several comments, some of which maybe were already part of the plan:

- We (Harvard people) are interested to learn the steps to run the simulation locally at Harvard.  Justo knows already the GEANT step, so the rest of the simulation would be our priority to learn.
- You mention graphics above.  I have prototyped a visualization tool (https://github.com/coreyjadams/ic-viewer) to help me understand the data formats and detector layout, I would be happy to get feedback and integrate this if people think it would be a useful tool.
- An overview (quite informal is no problem) of the flow of reconstruction of events would be tremendously helpful.  I would love to discuss the steps between raw data and physics analyses to understand what the current status is.

**Comment by jmalbos** [comment]
With respect to the migration to GitLab that you mention in this issue, have you explored the possibility of getting a free GitHub Team account? The user documentation indicates that ["Unlimited private repositories are free for verified students, teachers, and academic researchers"](https://help.github.com/articles/github-s-billing-plans/).

**Comment by jjgomezcadenas** [comment]
Hola Justo and Corey and Merry Xmass. Sorry about not answering first, this issue managed to escape my radar.

Quicks answers to your points:

>We (Harvard people) are interested to learn the steps to run the simulation locally at Harvard. Justo knows already the GEANT step, so the rest of the simulation would be our priority to learn.

Happy to discuss this during the Sprint week. Right now, the steps to simulation are still messy. We have a somewhat unholy combination of NEXUS (C++ Geant4) + DETSIM (C++ ART) + IC (Diomira). One of the on-oging projects is to move DETSIM to IC too. This project is assigned to @abotas. 

>You mention graphics above. I have prototyped a visualization tool (https://github.com/coreyjadams/ic-viewer) to help me understand the data formats and detector layout, I would be happy to get feedback and integrate this if people think it would be a useful tool.

Great! We definitively would like to go along this direction. I believe @jacg may want to interact with you guys concerning details of the implementation, but I think is a most promising start and we had no one to work on this, so we are happy that you step in.

> An overview (quite informal is no problem) of the flow of reconstruction of events would be tremendously helpful. I would love to discuss the steps between raw data and physics analyses to understand what the current status is.

Will do. This is a mandatory discussion, also in the context of the proposed re-factoring of the cities. More details during the Sprint. 

>With respect to the migration to GitLab that you mention in this issue, have you explored the possibility of getting a free GitHub Team account? The user documentation indicates that "Unlimited private repositories are free for verified students, teachers, and academic researchers".

Happy to look into this. I like GitHub (and I am already used to it). The main problem is LFS space/traffic. We can discuss also in the Sprint.

**Comment by jjgomezcadenas** [comment]
Sprint is over. Thanks to everybody
