### ISSUE TITLE
Fix comments which lie about test file contents etc.

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#419]
There are various places where comments have diverged from reality, and therefore mislead the reader. We notice these while working on all sorts of things, but never get around to fixing them.

This issue should serve as a place where we can note any such comments we find. Once a signifcant number of such comments has been noted here, We can fix a whole bunch of them in one go.

Please note any misleading comments you find (and do not have the time to fix immediately) by commenting in this issue.

**Comment by jacg** [comment]
`invisible_cities/conftest.py` in `TlMC_hits` and `TlMC_hits_skipping_NN` both lie in comments about the contents of the test data files.

**Comment by gonzaponte** [comment]
`invisible_cities/sierpe/blr.pyx` in `deconv_pmt`. The docstring lies about the return value. Dead pmts' waveforms are removed from the output, not filled with zeros.

**Comment by jacg** [comment]
@carmenromo Maybe you and/or Ryan could have a go at fixing these.

Everyone else: don't forget to mention any docstrings-that-lie, here.

**Comment by paolafer** [comment]
Type hint in `mcinfo.py` also lies in several places (`load_mchits`, `compute_mchits_dict`, `load_mcsensor_response`, `load_mcparticles`).

**Comment by carmenromo** [comment]
ok, I can look them @jacg! Ryan is on vacation

**Comment by carmenromo** [comment]
@jacg I fixed all the previous docstrings (even though in invisible_cities/conftest.py in TlMC_hits and TlMC_hits_skipping_NN I only removed the comments because I could not find out what particular issue does the test data file contain). Should I ask for the PR or should I wait if there are another comments to fix?

**Comment by jacg** [comment]
@carmenromo Please open a PR. That way people can have a look and see what you have done, and comment it.

Don't forget that it's not only comments and docstrings, but also some type annotations, such as those mentioned by @paolafer.

It's worth having your work visible to others in a PR, even if we expect more to be added to it later.
Seeing the PR open and being discussed, might remind others to conribute information about what else needs to be fixed, so don't delay opening the PR, then we can take it from there.

**Comment by jacg** [comment]
This issue has been upgraded to PR #498.
