### ISSUE TITLE
MC writer

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#422]
The mc writer receives the **whole table** rather than just a single event at a time, and it then performs a linear search through the table for each event. This seems seriously wrong.

@jjgomezcadenas claims that @jmbenlloch and @paolafer have a solution for this problem, consisting of adding an additional table with the extension of the events.

**Comment by jjgomezcadenas** [comment]
It turns out that the writer runs over the table but keeps memory of the event, so the problem does not exists.
