### ISSUE TITLE
Compare arrays of floating precision numbers

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#429]
When doing floating point numbers comparison we are using `pytest`'s `approx` function. This is convenient because *it tells you very explicitly what we are trying to check*. We have also extended this use to arrays and it seemed to work nicely. However, I have found 2 caveats:

- It doesn't work for multidimensional arrays.
- It can be ***extremely*** slow for (not-so-) large arrays.

I propose we implement our own `approx` function in `core/testing_utils` to keep the best of both worlds: the readability and elegance of `pytest`'s `approx` and the versatility and speed of `numpy`'s `allclose` function.

**Comment by jjgomezcadenas** [comment]
I am not sure I like this. We could simply stick to pytest for floats and to numpy which has a clear interface which we are extensively using for arrays. We have plenty of work to do and I find this unnecessary
