### ISSUE TITLE
Describe the "standard branch-fork-main-repository" development cycle

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#44]
I would like to document the standard sequence that a developer will follow to implement his contributions to the main repository. Here is the flow (tentative).

1) Developer opens a branch in his local (dev-branch)
2) Developer commits a sets of changes to dev-branch, until the task she has set to do is completed (n commits to dev-branch).
3) Developer squashes commits to n1 < n (offen n1 = 1), to clean up and tidy up the history of that particular development.
4) Developer pushes dev-branch to her fork (origin/dev-branch) and waits for Travis to approve.
5) Developer makes a pull-request.
6) If pull request accepted dev-branch is rebased to master in main rep  (icmaster)
7) Developer now fetches icmaster
8) Then rebases dev-branch on top of icmaster
9) Then deletes dev-branch
10) Finally deletes origin/dev-branch.

Could you experts please:

1) Confirm that sequence is correct, edit, add or subtract to sequence above (Jacek)
2) Describe how to perform tasks within magit (Jacek)
3) Describe how to perform tasks with raw git commands (JM? or simply cut-and-paste magit--git commands).

We need to nail down this procedure before opening to other collaborators or we will be in trouble...

**Comment by jacg** [comment]
My [``contributing`` branch](https://github.com/jacg/IC/tree/contributing) adds a `CONTRIBUTING.md` file which tries to address this, as well as a broader description of what is expected (tests!)

I was going to propose that JJ, JM & JG (a.k.a @jjgomezcadenas, @jmbenlloch and @jacg) hack on this (with pulls and pull requests) outside the `nextic` repo, in our own forks, before submitting a PR for the final product to `nextic`. But JJ has just requested (offline) that we open the repo up to other contributors right now, so perhaps a preliminary version should be included in `nextic` ASAP?

**Comment by jacg** [comment]
The branch has been renamed to `docs.contributing`, and the preliminary draft has been merged into the main `nextic` repo, so that the flood of new contributors to whom we are about to open the doors have something guidelines to work with. Nonetheless, much work remains to be done, including:

- Polish the existing text.
- Provide the git CLI version of the instructions.
- Talk about the `manage.sh` script.
- Think about the relationship between `CONTRIBUTING.md` and `README.rst`.

**Comment by jjgomezcadenas** [comment]
This is done in CONTRIBUTING.md.  Although it can be refined and expanded, the bulk of the work is done, I believe the issue can be closed.
