### ISSUE TITLE
refactoring of io of nexus MC h5 input files

### ISSUE THREAD

**Issue by jahernando** [next-exp/IC#444]
Refactoring of the nexus io files. Related with approval of PR #438. 

Improve readability, style and missing information in the nexus io readers. 

@paolafer @jerenner

**Comment by paolafer** [comment]
The PR has been reviewed and the necessary changes implemented.

**Comment by jacg** [comment]
I'm confused about the meaning and status of this issue? Can this be closed, now that #438 has been merged? Or does #438 being merged give the go-ahead to start on this?

**Comment by paolafer** [comment]
The mc info reader and writer functions have changed a lot since February and several PRs have been reviewed and approved, so my understanding is that this issue can be closed.

**Comment by jacg** [comment]
I take @paolafer's last comment as licence to close this issue.
