### ISSUE TITLE
test_compare_cwf_blr failing with a new test file

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#448]
Hi! I'm not sure if this is the place to bring up this issue, tell me if it's not.
I've almost completed the refactoring of the MC true reader and writer, and, in the process, I needed to generate again some of the test files, with the new MC format. I found a problem in just one test, namely `test_compare_cwf_blr`, where the assertion fails with the message:

`assert 0.22128403965346038 < 0.1`

Since I'm not familiar with blr calculation, can anybody help me to understand where the problem is? I have already changed the `n_baseline` parameter to the value actually written in the diomira configuration file used to generate this file.
 The same file is being used in other tests without errors. I attach the file if anyone wants to have a look at it:
[electrons_40keV_z250_RWF.h5.zip](https://github.com/nextic/IC/files/1756407/electrons_40keV_z250_RWF.h5.zip)

**Comment by jjgomezcadenas** [comment]
This test compares the waveform "true" (that is passed by the electronics but without the HPF, which we call BLR, with the Corrected Waveform (CWF) which one recovers by deconvolution. It compares the areas of both signals, which must be very close. There is no reason why your changes should have altered this test. We can look together at the issue tomorrow.

**Comment by jjgomezcadenas** [comment]
I think this is an old issue, and can be closed now.
