### ISSUE TITLE
Masked channels in MC simulation

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#451]
In the current code, masked SiPM channels are being simulated, with zero signal, but not zero noise. However, they should not be there at all. @andLaing, could you add this to your PR?

**Comment by andLaing** [comment]
You mean the one with the changes for the sensor simulation?

It'll be submitted once the current one's accepted and I can rebase on all the useful changes it has for assessing the output. I'll look into the masked channels and consult with you when I have the changes you request made.

**Comment by gonzaponte** [comment]
Mmm. The masking for the sipm simulation is in place. Can you please post
here the run number and the sipm index or id that should be masked and is
not?

**Comment by paolafer** [comment]
Looking at the `simulate_sipm_response()` function in `sensor_functions.py` it seems to me that all the SiPM waveforms are taken, am I wrong?

**Comment by gonzaponte** [comment]
The noise sampler has a masking function.

**Comment by paolafer** [comment]
Ok, then. Regarding the PMTs, in which part of the diomira code are they masked? I couldn't find it, but they must be masked, otherwise the loop in `simulate_pmt_response` should fail...

**Comment by gonzaponte** [comment]
I think they are "accidentally" masked because the adc_to_pes constant is 0
for those pmts. Anyway in #431 some issue with diomira and masked channels
is addressed. Maybe that's what you are talking about.

**Comment by paolafer** [comment]
Actually, I think that the crash should happen before, in the loop over the `NPMT` sensors in `simulate_pmt_response`. This number should always be 12, because `NPMT = pmtrd.shape[1]`, but `adc_to_pes` should have only 11 elements, because in `base_cities`, we have:

`self.pmt_adc_to_pes = self.pmt_adc_to_pes[pmt_active]`

What am I missing?

**Comment by jjgomezcadenas** [comment]
I think pmt_active is not upated in the DB and always has 12 elements. Then, since the corresponding adc constant for the dead PMT is (accidentally) zero, the error passes.

Probably pmt_active is not needed, enough with setting the constant of the dead PMT to zero.

**Comment by paolafer** [comment]
Actually, `pmt_active` is updated and the code is broken. I haven't realized so far, because I was using Andrew's branch noiseSiPM, which is previous to the pmaps refactoring. 
With the current master, if one uses a run number for MC which is related to a data run number of run II, the loop in `simulate_pmt_response` crashes when trying to access the dead PMT.

**Comment by gonzaponte** [comment]
> With the current master, if one uses a run number for MC which is related to a data run number of run II, the loop in simulate_pmt_response crashes when trying to access the dead PMT.

And that is fixed in #431, isn't it?

**Comment by paolafer** [comment]
Ah, sorry, I forgot to look at it :-). If it is fixed, I think that that PR should be approved and merged as soon as possible. Is there any reason why it is waiting?
