### ISSUE TITLE
Trigger parameters required even when no trigger

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#453]
Is there a way to avoid writing in the configuration file the values needed for the trigger, when `trigger_type = "None"` is selected? This would be a more sensible behaviour, I think, instead of using random values.

**Comment by jacg** [comment]
Definitely possible. I'd need to look at the code (for which I don't have time) to figure out a good way of doing it. But, assuming that you are talking about a city created with `@city`, then you could give default values of `None` in the parameter list of the city for  all parameters that relate to trigger configuration, and inside the function raise an exception if any of them are `None` unless `trigger_type is None`.

This is all off the top of my head without seeing the code, so I might be barking up the wrong tree.

**Comment by paolafer** [comment]
I will try to do as you suggest. I will have to understand how the configuration works, since it's one of the aspects of IC that are still obscure to me...

**Comment by gonzaponte** [comment]
It will be possible with the liquid cities, but not (at least it is not obvious) with the solid ones.

**Comment by jacg** [comment]
You mean the solid ones are still around?

**Comment by gonzaponte** [comment]
That is the case, unfortunately. Too many other things to work on. But they are 99% ready to be removed. I have in my fork the liquid version of #440, but I still need to make sure they are correct.

**Comment by paolafer** [comment]
So, do you suggest to wait until cities are liquid, before attempting to make this change, right?

**Comment by jacg** [comment]
Unless I'm missing something, I think it would be a waste of time to do anything in the solid cities at this point.

**Comment by gonzaponte** [comment]
Closed by the implementation of liquid cities.
