### ISSUE TITLE
Local database and updates

### ISSUE THREAD

**Issue by andLaing** [next-exp/IC#461]
I've had some issues again (and I think it's happened to everyone at least once) that I've discovered that I hadn't updated the local copy of the database.

Is there any way that the test suite or similar could check if an update is necessary? This will become more of an issue when more people are writing analyses I suspect so it might be the time to add something.

**Comment by jacg** [comment]
This is not the test suite's job: it is the job of the version control system. As we do not want binaries to be stored directly in Git, we need a Git LFS server. This has all been discussed and agreed months ago (#210), and in January we reviewed specific implementation strategies and agreed on the way forward: we are just waiting for it to actually be put into practice.

@jjgomezcadenas Any news on progress?

**Comment by jjgomezcadenas** [comment]
No, unfortunately this very important matter is not being addressed due to lack of man power. I hope we will be able to address it once the current rush of analysis, papers and crazy time passes.

**Comment by andLaing** [comment]
Hi

I understand that what you suggest and is detailed in the other issue is the most complete and correct implementation but is it not possible to check if the local copy is present and the same as the mysql version? Maybe I'm mixing things but there is a bash script in frontend1next which checks that the localhost copy is the same as the server, I've put it here: http://next.ific.uv.es/DocDB/0005/000584/001/checkDBSync.sh

the usual passwords...

Please ignore me and close the issue if I've got the wrong end of the stick, highly probable.

A

**Comment by jacg** [comment]
Sorry, I don't have access rights to this URL.

Yes, you could add some sort of check somewhere, presumably for the purpose of spotting that other problems are being caused by use of the wrong version of the database.

I think that there is an argument for making it as painful as possible, so that it pisses off as many people as much as possible, so that sorting out Git LFS rises towards the top of everybody's priority list: It's long overdue!

**Comment by jacg** [comment]
I need to point out that here is yet another issue which has been open for 4 months, but wouldn't have arisen if Git LFS were available. As it stands, people are going to continue to be bitten by it, and waste precious time ... until Git LFS is available.

**Comment by jacg** [comment]
Has Git LFS solved this particular problem?

**Comment by gonzaponte** [comment]
Seems like including the database in the repository via LFS has addressed this particular issue.
