### ISSUE TITLE
Silence warnings

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#484]
5c7125f2a669439d64d3d2bfbb331514830212bf (the second commit of #434) introduces screenfuls of warnings like this:

    envs/IC3.6/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: '0BsIflpz5M2'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
    NaturalNameWarning)

This pretty much ensures that if a meaningful warning ever appears somewhere nearby, it will not be seen, as it will be completely drowned out by this noise. So these warnings need to be silenced.

This might be an interesting task for someone who has not yet had a PR accepted into nextic: it will probably not require involved coding, but will serve as practice in the nextic PR cycle.

**Comment by jjgomezcadenas** [comment]
Nothing is being done here, and the warnings are extremely annoying. This needs to be fixed urgently, if no other volunteers by the author of of the commit.

**Comment by Aretno** [comment]
At @jjgomezcadenas request I patched the thing at #487. (Sorry, didn't see this issue before aside from some email from him).
