### ISSUE TITLE
numpy 1.13.1 not compatible with keras

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#499]
I have found almost by chance that numpy 1.13.1 (our default in IC) is not compatible with keras under conda (anaconda) installation. How do you handle this, @jerenner? To use keras, conda environment downgrades numpy to 1.12 and then one of our tests do not pass (there is some numpy functionality missing).

**Comment by jacg** [comment]
In order to be able to react productively to issues like this, we really need to review and approve #496 (or some variation on the theme). How are you getting on with the failing test in #496 @jjgomezcadenas?

**Comment by jerenner** [comment]
I think there may be a way to force the use of numpy 1.13.1 - it should still work with keras.  I'm not sure what the exact command is but I can look for it.

**Comment by jerenner** [comment]
Do we have to install with `conda`?  Installing with `pip` does not seem to require the downgrade.
