### ISSUE TITLE
Errors in tests after installing new environment

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#519]
I've followed the instructions given in #518, namely:
- Delete my conda installation.
- Install a new one.
- Do `source /Users/paola/Software/miniconda3/etc/profile.d/conda.sh`.
- Do `conda activate`.
- Do `source manage.sh work_in_python_version 3.6`.

No errors appear in the progress of the tests (all nice green PASSED are all around), but at the end I got 21 errors related to libraries of sqlite3 or matplotlib. The errors are like this one:
[error.txt](https://github.com/nextic/IC/files/2244822/error.txt).
Any idea of what can be happening?

**Comment by jjgomezcadenas** [comment]
It sounds as if you have another python version interfering with your setup. if you type python and enter the REPL, is that the python provided by ANACONDA?

**Comment by paolafer** [comment]
If I type python, I get

`Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)`

so I guess that it's working fine, right?

**Comment by paolafer** [comment]
I've also tried to install an environment for python 3.7, but the error stays.

**Comment by paolafer** [comment]
I have reinstalled the whole OS in my laptop (macOS 10.13.6, the same as @andLaing, who has no problem), according to the suggestion of @jjgomezcadenas, and installed miniconda from the scratch. Still, tests keep failing, with the same errors. I'm using conda version 4.5.9.
I follow these steps:

- source /Users/paola/miniconda/etc/profile.d/conda.sh.
- conda activate.
- source manage.sh work_in_python_version 3.6.

I'm currently unable to work and I don't know what to do. Could anyone help me, please?
I attach again the first error of the series.
[error_Aug8.txt](https://github.com/nextic/IC/files/2270716/error_Aug8.txt)

**Comment by paolafer** [comment]
Update: I tried to run a city (penthesilea) and apparently it runs normally. However, if I try to open a Jupiter notebook, it crashes miserably with the following error:

Traceback (most recent call last):
  File "/Users/paola/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 10, in <module>
    import sqlite3
  File "/Users/paola/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/Users/paola/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/Users/paola/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/lib-dynload/_sqlite3.cpython-36m-darwin.so, 2): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /Users/paola/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/lib-dynload/_sqlite3.cpython-36m-darwin.so
  Expected in: /usr/lib/libsqlite3.dylib
 in /Users/paola/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/lib-dynload/_sqlite3.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paola/miniconda/envs/IC-3.6-2018-07-29/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/paola/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/site-packages/notebook/notebookapp.py", line 85, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/Users/paola/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 13, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

**Comment by jjgomezcadenas** [comment]
I am afraid that you need a real installation from scratch.  The problem is that the new system is probably sitting on top of some old libraries that are creating the problem. I had a similar issue with my old power book. 

The way I solved was with a clean installation, meaning:

1. full erase the disk.
2. Reinstall operative system from scratch
3. Install IC

**Comment by paolafer** [comment]
@jjgomezcadenas, this is exactly what I did.
Anyway, @andLaing found the solution, googling around, and it was a problem of the DYLD_LIBRARY_PATH variable (https://github.com/ContinuumIO/anaconda-issues/issues/7713). Once fixed that, it seems that everything works. Thanks, Andrew, for all your help!

**Comment by jjgomezcadenas** [comment]
Great, and let's keep this issue clearly in mind for next time!
