### ISSUE TITLE
Install dataclasses in python 3.6

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#523]
@jacg could you add a line to the install script to install dataclasses in python 3.6 (can be done with pip). Although dataclasses are python 3.7, we may need a while until we phase out 3.6. @mmkekic has submitted a PR using dataclasses and I believe we should not wait until python 3.6 is outdated. Is just a line.

**Comment by jacg** [comment]
> Is just a line.

I wish I shared your optimism!

Given that dataclasses are built in to Python 3.7, I doubt that the package exists for 3.7, so adding it to the dependencies is likely to make the build for 3.7 fail. This opens the can of worms that is different dependencies for different Python versions ... which has been lurking in the back of my mind for a while ... and our dependency tracking mechanism simply doesn't cater for at present.

Besides, if it is just a line, then just go ahead and do it! There's no need to wait for me to find the time for it, which I certainly don't have right now.

**Comment by jjgomezcadenas** [comment]
I see. 
Wel, I won't touch manage.sh. I have enough in my platter already. We can as well live without introducing dataclasses in python 3.6 if we tolerate test fails in python 3.6 related with dataclasses.

**Comment by jacg** [comment]
> I won't touch `manage.sh`

The mere thought makes me nauseous too.

> We can as well live without introducing dataclasses in python 3.6 if we tolerate test fails in python 3.6 related with dataclasses.

`@skipif(sys.version_info < (3,7), ...)`?

One minor problem is that 3.6-on-Linux is the only build that isn't allowed to fail, at the moment. If we skip a bunch of tests on the only required build, then we're punching a hole in our test suite. So perhaps we should make 3.7 required too ... or maybe even drop 3.6.

Skipping the tests on 3.6 doesn't get us very far though: if anyone starts using the utilities which rely on dataclasses, then that doesn't solve the problem: we will either have to fully migrate to 3.7, or solve the problem of inconsistent dependency configuration across different Python versions, so we're back to square one.

**Comment by gonzaponte** [comment]
We've already moved to 3.7.
