### ISSUE TITLE
Warning running diomira

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#526]
After updating IC I started getting the following warnings, running diomira:

/home/paolafer/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/site-packages/mkl_fft/_numpy_fft.py:1044:  FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output = mkl_fft.rfftn_numpy(a, s, axes)
/home/paolafer/miniconda/envs/IC-3.6-2018-07-29/lib/python3.6/site-packages/scipy/signal/signaltools.py:3463: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

Should we worry about this?

**Comment by jjgomezcadenas** [comment]
Yes, I believe we should start to worry and chase/fix the code where relevant.

**Comment by gonzaponte** [comment]
Fixed in #554.
