### ISSUE TITLE
Tolerance in paolina voxels

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#533]
The `test_voxelize_hits_gives_maximum_voxels_size` in `paolina_functions_test.py` test needs a tolerance of some epsilon (12 * 10^-12 has been demonstrated to work) in order to pass. It is not clear why it is so, and this should be understood.

**Comment by gonzaponte** [comment]
@paolafer Has this issue been addressed in #532 or should we leave it open?

**Comment by paolafer** [comment]
No progress has been done on this, I'm afraid...

**Comment by paolafer** [comment]
I've found another issue related to the tolerance of paolina voxels, which is the following.
We have added the tolerance to avoid that hits inside voxels at the boundaries of the histogram used to create them fall exactly on the border of the voxel. However, it happens that hits fall exactly on the border of voxels which are not at the boundaries. This happens systematically when the hits are regularly spaced, for instance in the case we assign a hit to each SiPM over a threshold. 
We could simply ignore this behaviour (who cares if a hit is assigned to a voxel or its neighbour?) if we didn't use the fact that a hit belongs to a particular voxel, as we do, for instance, when we build the blobs or when we eliminate voxels under a certain energy threshold.

I think that the safest way to deal with this is to assign to the Voxel instance a list of associate hits, at the moment of the voxel creation, which is where we know about the tolerance used, and the mechanics of the `numpy histogramdd()` function, which uses [,) boundaries for all the bins, except for the last one, which is [,]. This way, the user of voxels doesn't need to decide if a hit belongs to a certain voxel or another one, and decide if to use `<`, `<=`, `np.isclose` with which tolerance....
Still, if the numpy developers should change this behaviour, we are in trouble, I guess...

I summon @jacg here, if he has time to give his opinion.

**Comment by jjgomezcadenas** [comment]
I suspect @jacg doest not have the time. Here my five cents. I agree best is to assign the list of associate hits to the Voxel instance at creation time. I would not use a hard-wired feature to assign hits to voxels if a high-level feature is available (e.g, np.isclose).

**Comment by jacg** [comment]
Hello ... I hear you ... unfortunately I simply won't have the opportunity to string together more than 30s of uninterrupted thought to dedicate to this issue for at least a couple of weeks, and I'd need more than 30s.

**Comment by mmkekic** [comment]
Fixed with #642
