### ISSUE TITLE
S1 collection 

### ISSUE THREAD

**Issue by jahernando** [next-exp/IC#534]
**About how to incorporate S1 information into high-level output hdf5 files** (i.e the output of `Penthesilea`).

The philosophy is to add new code in a way that can be used in *dataflow*, and if needed, modify minimally the existing code to use this new code.

@jerenner and I we discussed this strategy:

1. define data-structures and functions: `S1Collection, create_s1collection, write_s1collection`. `S1 collection` is a simple data-estructure which contains the information of the S1s per event (one raw for each S1, labeled by run/event number), `create_s1collection` creates the `S1Collection` from `pMaps`, `write_s1collection`, write `S1collections` (that is a simple table labeled by run/event) into a hdf5 output file.

2. incorporate the creation of `S1Collection` into `Penthesilea`. Modify the `create_dst_event` method to create `HitCollection` and `S1collection`.

3. (Optionial) Modify `Dorothea` to create the kdst entries using `S1Collection`, (this is here to guarantee that we all use the same code).
 
We will proceed with this plan but comments, critics are welcome.

**Comment by jahernando** [comment]
Discussing with the @jjgomezcadenas and @jmbenlloch, they proposed to access S1 information via the kdst. That implies that for physics stream `Dorothea` and `Penthesilea` must run over `Pmaps` with the same filter of events. They will produce their hdf5 outputs (kdst, hdst) and it is responsibility of the client to read the S1 information from the kdst and the hits information from the hdst.

The main advantage of this solution is that it does not require to add new code in IC, at the price of incorporating a second `Dorothea` in the processing of the `Physics/Trigger2` data stream. We need to ensure in adition that `Dorothea` and `Penthesilea` have the same filter of events.

**Comment by jjgomezcadenas** [comment]
It turns out that @gonzaponte and others prefer to modify the hdst. This would require reprocessing, but on the other hand it would be a good opportunity to test the new liquid cities. So I would agree to go this way, if everybody is happy with it.

**Comment by mmkekic** [comment]
Resolved in  #574
