### ISSUE TITLE
Review skipped tests

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#560]
In order to speed the process of refactoring liquid cities, we have skipped a number of troublesome tests. Many of them are histograms, which need to go to a different place (separate issue) but all the rest need to be reviewed. I propose that this is done by @bpalmeiro, and @carmenromo (with the guidance of @gonzaponte). "Review" here means identifying the author of the skipped test and ask him or her to fix it, then keep log of the tests that are being fixed. Please proceed without delay, this is an important issue that should not be left hanging.

**Comment by carmenromo** [comment]
ok, but which tests do you mean @jjgomezcadenas? All the skipped tests or those of PR 559?
