### ISSUE TITLE
Move Histogram Monitor to a different repo

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#561]
Histogram Monitor is a rather clear case of a "client", which uses functions from IC, but produces output that has little to do with IC (no transformation of the IC data flow). After discussion with @jacg and in order to simplify IC and to lighten the number of tests, we propose that Histogram Monitor is moved to a separate repository (like KrCalib). Please @jmbenlloch, create this repository and please @Aretno, move code and tests there. The repo must be Travis-enabled, and the usual way to interact with the repo must be identical to IC (via PR, etc.).

**Comment by Aretno** [comment]
Let me know when the repo is set up, @jmbenlloch.

**Comment by mmkekic** [comment]
I assume this is done in Olivia @Aretno ?
