### ISSUE TITLE
Making calibration pretentious

### ISSUE THREAD

**Issue by andLaing** [next-exp/IC#566]
Just a request that before the new liquid cities are installed on frontend1next etc that whoever's doing it tells us so that we can update the shiftertools with the new meaningless empty names for calibration cities otherwise we'll have problems when the next calibration data is processed.

An aside related to this, could the chief instigator maybe add a comment to the cities and a README or similar with a line with a basic description of what the cities do? I could only work out which name went where (I think) because I know what the standard outputs of the calibration cities are. New users will not be able to understand the functionality of any city without a good understanding of the current selection/analysis.

**Comment by jjgomezcadenas** [comment]
Let me blame on somebody else. @gonzaponte would you kindly add a section to our README describing the functionality of the cities? You know as much as I do (or more) about the classical one and YOU are the one that dared renaming the Scottish cities (mind you, at your risks and perils). So humour me, please and mitigate the just ire of our dearest Northerner, amen.

**Comment by gonzaponte** [comment]
Closed by #568.
