### ISSUE TITLE
`event_range = 0` doesn't work

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#573]
I was trying to run `diomira` with `event_range = 0` for a test and it crashes.

- Is this behaviour expected?
- Should it be fixed?

**Comment by jjgomezcadenas** [comment]
Diomira is not supposed to run with event_rang=0, but probably we want to add a protection so that it insults nicely the user (something like: you moron, want me to run with no events? ) and exit, rather than crashing. Same for other cities.

**Comment by gonzaponte** [comment]
Well, it is not completely clear to me whether we should allow it or not. From my experience, I think it could be a way of testing the cities "initialization process", that is, everything before `dataflow.push`.  In particular, I've found this situation while trying to add a test for #570. I wanted to run  `diomira` with no events so it doesn't draw random numbers, but it does run the part of the code were the seed is established.

**Comment by jjgomezcadenas** [comment]
Sounds to me as too technical. Normal user should not run diomira with event_range=0, I believe.
