### ISSUE TITLE
Peak.width gives wrong width

### ISSUE THREAD

**Issue by andLaing** [next-exp/IC#584]
Checking the output vs config for some PMaps the other day I found a mismatch between the minimum width set in the configuration  for s1s and the minimum width in plots of s1.width

I consulted with @gonzaponte and checked the code and it seems that the width_above_threshold function doesn't give the width but the difference between the first and last time which for the 25 ns bin s1s (no rebin as standard) results in width - 25 ns.

General implementation of the correct function is complicated since a rebinned Peak (like the S2s) has the weighted mean of each sample as its time array so we may need to add more info to the Peaks, an array of sample widths or something...

**Comment by mmkekic** [comment]
Solved in #593
