### ISSUE TITLE
Parametrized algorithm for xy reconstruction

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#587]
I'd like to bring up again the matter of being able to choose a particular algorithm for xy reconstruction, via configuration parameter. Right now, I'm testing variations of corona and also different algorithms and I think that it would be better to have a code with several options, at least for a while.
In the ancient times, we had this possibility, but it was removed at some point.
If you agree, I volunteer to implement the code to do this.

**Comment by jjgomezcadenas** [comment]
This would go in Penthesilea, right?

**Comment by paolafer** [comment]
It would be used in Penthesilea, yes.

**Comment by msorel** [comment]
I think this is an excellent idea!

**Comment by jjgomezcadenas** [comment]
Agreed. See also #591
