### ISSUE TITLE
Proposal to reorganize data formats 

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#590]
This proposal comes after:

1) Discussions with @gonzaponte, concerning what to do with empty PMAPS: we did realize that it is better NOT TO THROW THEM AWAY, but rather add a mask filter specifying that the PMAP is not good (e.g, a vector with 1 for good pmaps 0 for empty pmaps). In this way we can try to traceback using the MC why a given event results in an empty PMAPS.

2) Working in Esmeralda (con peras, @mmkekic and @jjgomezcadenas). We realize that:

1. It would be preferable not to throw events that do not pass filters (after PMAPS), but rather keep them with the corresponding mask per filter (1 if passed 0 if not passed). This allows tracing back the reason for a filter failure. 

2. The current structure of liquid cities wants to yield a stream of data per event. In the case of (for example) the hit-dst (which is a square table) the way we implement it is: a) reading the hdst as a pandas DataFrame (this is actually pretty fast); b) fill a "transient" HitCollection instance which is actually another container (organized by raw rather by a column). To do this we perform an **ugly** loop just to recopy data from one arrangement to the other (we do this in *load_hits()*; c) Then we can yield event-by-event the hits contained in the hit collection. But step 2 is utterly unnecessary. We can directly slice the DataFrame obtained in step (a).

3. The way we store Monte Carlo information is messy. The reason is that we use tables that are not squared. This forces us to pass the whole MC table (which is really at odds with the yield philosophy of liquid cities), but also impose pretty ugly manipulations to navigate those tables. Instead, if we would have squared tables these could be read as DataFrames and passed event-by-event in perfect correspondence with the data (in particular if we don't throw anything away). 

Thus we propose the following:

For kdst. Current structure is:
```
class KrTable(tb.IsDescription):
    event   = tb.  Int32Col(pos= 0)
    time    = tb.Float64Col(pos= 1)
    s1_peak = tb. UInt16Col(pos= 2)
    s2_peak = tb. UInt16Col(pos= 3)
    nS1     = tb. UInt16Col(pos= 4)
    nS2     = tb. UInt16Col(pos= 5)

    S1w     = tb.Float64Col(pos= 6)
    S1h     = tb.Float64Col(pos= 7)
    S1e     = tb.Float64Col(pos= 8)
    S1t     = tb.Float64Col(pos= 9)

    S2w     = tb.Float64Col(pos=10)
    S2h     = tb.Float64Col(pos=11)
    S2e     = tb.Float64Col(pos=12)
    S2q     = tb.Float64Col(pos=13)
    S2t     = tb.Float64Col(pos=14)

    Nsipm   = tb. UInt16Col(pos=15)
    DT      = tb.Float64Col(pos=16)
    Z       = tb.Float64Col(pos=17)
    Zrms    = tb.Float64Col(pos=18)
    X       = tb.Float64Col(pos=19)
    Y       = tb.Float64Col(pos=20)
    R       = tb.Float64Col(pos=21)
    Phi     = tb.Float64Col(pos=22)
    Xrms    = tb.Float64Col(pos=23)
    Yrms    = tb.Float64Col(pos=24)
```
This is a square table (Thus a DataFrame). We propose to add 3 fields which are boolean vectors. In fact those fields are already present in the S1S2Selector:
```
        - passed  : a boolean flag indicating whether the event as
                    a whole has passed the filter.
        - s1_peaks: a sequence with a boolean flag for each peak
                    indicating whether the peak has been selected
                    or not.
        - s2_peaks: same as s1_peaks.
```
We simply need to write the vectors.

For hdst is the same story. It is a square table 
```
class HitsTable(tb.IsDescription):
    event    = tb.  Int32Col(pos=0)
    time     = tb.Float64Col(pos=1)
    npeak    = tb. UInt16Col(pos=2)
    Xpeak    = tb.Float64Col(pos=3)
    Ypeak    = tb.Float64Col(pos=4)
    nsipm    = tb. UInt16Col(pos=5)
    X        = tb.Float64Col(pos=6)
    Y        = tb.Float64Col(pos=7)
    Xrms     = tb.Float64Col(pos=8)
    Yrms     = tb.Float64Col(pos=9)
    Z        = tb.Float64Col(pos=10)
    Q        = tb.Float64Col(pos=11)
    E        = tb.Float64Col(pos=12)
    Ql       = tb.Float64Col(pos=13)
    El       = tb.Float64Col(pos=14)
    Qc       = tb.Float64Col(pos=15)
    Ec       = tb.Float64Col(pos=16)
    Zc       = tb.Float64Col(pos=17)
```
And the only thing that we need to add are the filter information, which is basically the same than for the kdst (maybe one extra boolean vector corresponding to the condition 1 S1). 

For MonteCarlo hits

```
class MCHitInfo(tb.IsDescription):
    """Stores the simulated hits as metadata using Pytables.
    """
    hit_position  = tb.Float32Col(    pos=0, shape=3)
    hit_time      = tb.Float64Col(    pos=1)
    hit_energy    = tb.Float32Col(    pos=2)
    label         = tb. StringCol(20, pos=3)
    particle_indx = tb.  Int16Col(    pos=4)
    hit_indx      = tb.  Int16Col(    pos=5)
```

The only reason why this is not a squared table is hit_position. Simply replace this field by three fields
(x,y,z) and we have a nice square table that maps to a DataFrame. We also want to add the event number and time stamp. 

for Monte Carlo Particles:
```
class MCParticleInfo(tb.IsDescription):
    """Stores the simulated particles as metadata using Pytables.
    """
    particle_indx  = tb.  Int16Col(    pos=0)
    particle_name  = tb. StringCol(20, pos=1)
    primary        = tb.  Int16Col(    pos=2)
    mother_indx    = tb.  Int16Col(    pos=3)
    initial_vertex = tb.Float32Col(    pos=4, shape=4)
    final_vertex   = tb.Float32Col(    pos=5, shape=4)
    initial_volume = tb. StringCol(20, pos=6)
    final_volume   = tb. StringCol(20, pos=7)
    momentum       = tb.Float32Col(    pos=8, shape=3)
    kin_energy     = tb.Float32Col(    pos=9)
    creator_proc   = tb. StringCol(20, pos=10)

```
Needs a few more fields to replace initial_vertex, final_vertex and momentum, but still worth to do it and get a squared table. Plus adding event and timestamp info.

With those propose changes we would achieve:

1. Consistency in selection: data is not thrown away by the cities, but passed along with a flag indicating status. One can later trivially select interesting events.

2. Consistency in format: everything is a squared table (e.g, a DataFrame) and can be yielded event by event easily. Plus everything is connected by event number/time-stamp.

**Comment by mmkekic** [comment]
I dont think there are any plans to change the outputs of the old cities, so I close this issue for now.
