### ISSUE TITLE
Hit or corona?

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#591]
After the last round of results from @paolafer the question arises whether we should keep corona as default or try 1-hit-per-sipm. This is a non-trivial decision, in the view of data-processing coming up and we should try and understand what is the best approach.

**Comment by msorel** [comment]
@jjgomezcadenas Related to our recent discussions on how to reorganise communications among NEXT Collaboration...

I guess you meant this comment to appear as a comment to this Teamwork Notebook:
https://nextbb.teamwork.com/#notebooks/168825
or somewhere else on Teamwork or on mailing lists. And not as a new Git Issue (nor Slack)

Right? 

The more technical aspect on how to generalise software to deal with multiple hit definitions does belong to Git Issues, and this can be addressed in #587 opened by @paolafer 

With so many communication channels available to us and non-overlapping subsets of people signed up to each one of them, we need clear rules, not to keep relevant people out of the discussion loops.

**Comment by jjgomezcadenas** [comment]
>I guess you meant this comment to appear as a comment to this Teamwork Notebook:
https://nextbb.teamwork.com/#notebooks/168825
or somewhere else on Teamwork or on mailing lists. And not as a new Git Issue (nor Slack)

Well, not totally obvious. Certainly not slack. But 1-hit-rather than corona has implications for software, so I think it belongs actually to both Teamwork and git. 

>With so many communication channels available to us and non-overlapping subsets of people signed up to each one of them, we need clear rules, not to keep relevant people out of the discussion loops.

Yes. I believe that Teamwork and github are, however, rather connected, and some duplication may be inevitable. Agree, however, that this issue must also go to Teamwork.

**Comment by jjgomezcadenas** [comment]
Further to my previous comments, here a new proposal (and the reason why this issue is open in Github now becomes evident). 

I believe that the solution to our dilemma is not Hits OR Corona, but Hits AND Corona. I propose that Penthesilea writes TWO hits tables, one with the corona hits, the other one with one hit per SiPM touched. Like this we have all the available info for further analysis downstream.

**Comment by msorel** [comment]
Considering where we are, with dust still not settled, I agree it could be more prudent to provide different hit definitions to analysers, but all of them through "official" productions

My main question and possible twist to what you have here is: 

- one penthesilea job filling two hit tables, same format for both tables but filled with different XY algorithms? I understand this is your proposal. Or...

- two penthesilea jobs, each one filling one hit table, according to a configurable XY reconstruction algorithm? This is linked to #587 , which I support

I have a preference for the second option, as it gives more flexibility. Note we do not have just "SiPM" and "corona" hits. we already have a "modified corona" XY algorithm and tomorrow we will probably have a "modified2", etc.. Trying to encapsulate all that in a single penthesilea job will not be elegant

What does this mean in practice? Assume we carry through official production two XY reconstruction algorithms at most for now (which is the sensible thing to do I believe, as you say). In this case, we could run two penthesilea jobs on each PMAP input file. I do not think this will be much slower than filling two tables in one penthesilea job.

Again, we would need to be careful of applying same event selection in both.

In terms of file size, since hits information should dominate, it should not be a big deal to rewrite some info twice, in two different files.

Note that I am assuming that the SiPMhit-based hit table and the corona-based hit table have the same format, otherwise my scheme does not work. But I believe this is the case, right?

**Comment by jjgomezcadenas** [comment]
>I have a preference for the second option, as it gives more flexibility. Note we do not have just "SiPM" and "corona" hits. we already have a "modified corona" XY algorithm and tomorrow we will probably have a "modified2", etc.. Trying to encapsulate all that in a single penthesilea job will not be elegant

The reason why I suggest two tables is that I believe that energy reconstruction and topology reconstruction will not be optimized by the same algorithm! Thus, one (I believe corona) will be used for energy reconstruction, a second table (hits) for topology (of course one can also use the first table for topology).

In the scheme I propose one can still configure the reco algorithm and use modif-corona instead of corona, but always keep the basic table of sipm-as-hist (eg, "no reco"). Thus both options are not incompatible. I advocate for two tables and then if we want to try different reco algos, we do different productions (but always keep the "sipm-as-hits" table).

**Comment by msorel** [comment]
Ah, OK, I see your point. For the "sipm-as-hits" table to be conceptually different as "corona-as-hits" table and not imply reconstruction, in my mind two conditions should be met:

- no parameters (configurable or hardwired) enter in the definition of a "sipm-as-hit"

- no data reduction compared to what already present at the PMAP level

In this case, we are in a similar situation as converting binary to hdf5 BLR waveforms, if you like. No data manipulation beyond technical. Such a hit table would indeed be conceptually different from a  reconstructed hit table and I think it would be valid to write two tables in the same penthesilea job.

This is not what I thought you intended at first. If the "sipm-as-hit" table is built with:
_Loop over SiPM hits in the time slice that have made it to the PMAP, **and write those as penthesilea hits only if they have a charge greater than some PE threshold**_
where the threshold can be 30 PEs, 10 PEs or some other number, then conceptually this is just another reconstruction algorithm as corona or modified corona. Even if a very simple one. In fact, as you know, we will precisely be looking at optimising this threshold (non-trivial), either in reconstruction or analysis. In this case, I think writing one hit table per penthesilea job makes more sense

On the other hand, if the data manipulation to build the "sipm-as-hit" table is simply:
_Loop over SiPM hits in the time slice that have made it to the PMAP, **and write all of them as hits**_
and assume all SiPM charge threshold studies are done at analysis stage and not reconstruction stage, then I think it is fair to call this "no reconstruction", treat it differently from "corona", "modified corona", etc. algorithms and write two tables in same job. If one wants to change this "sipm-as-hit" table, then one is forced to run irene and build PMAPs with other threshold in irene. No threshold or other configurable parameter to speak of in penthesilea for this, which is cleaner

Do you agree? The latter approach is fine with me, provided we can tolerate the increased file size. How many SiPM hits make it to the PMAP stage and per time slice, typically? Is this "sipm-as-hit" hit table going to be one order of magnitude larger than the "corona-as-hit" hit table? Two orders of magnitude? Can somebody estimate the numbers?

We only run penthesilea on low-bgr data and HE calibration data. Low-bgr data is probably a smaller concern, as we acquire only ~8,000 triggers per day. The most constraining condition will probably come from HE calibration data, where we acquire ~300,000 triggers per day.

**Comment by jjgomezcadenas** [comment]
Yes, I want to use a cut on SiPM. This is obvious, since we need to get rid of the dark current and does not imply any particular reconstruction. It can be envisioned at the same level that we put cuts on S1 or S2 samples to form the S1/S2 waveforms. 

Taking all the SiPms that have a charge above threshold (threshold can be defined at some convenient level, perhaps not very strict, say 99 % or 3 pes) is not really performing reconstruction, you just keep all the raw info that you can manipulate later. It is at a very different level than other reco algorithms that manipulate the hits. So, yes, I still want to have a parameter (sipm_thresh = 3-10 pes to be studeid) and I don't think we do any data reduction (alll events that come out of PMAPS will pass). 

Keepint the threshold cut is still a good idea, to avoid hard-wire-numbers, but it is understood that we have agrees in a threshold that biases minimally the data (while eliminating some 99 % of the SiPMs). 


>How many SiPM hits make it to the PMAP stage and per time slice, typically? Is this "sipm-as-hit" hit table going to be one order of magnitude larger than the "corona-as-hit" hit table? Two orders of magnitude? Can somebody estimate the numbers?

It depends on the SiPM cut. at 99 % you let 1 % of the noise pass, eg, 20 hits per slice. At 99.9  % (easy to implement and little bias) you will have like 2 per slice. I don't think size should be aproblem here.

**Comment by msorel** [comment]
@jjgomezcadenas if it is all about cutting noise before writing "raw hits" (that is, "pmap hits"), then I still think that the best thing to do is to cut said noise in irene and not introduce a second set of thresholds in penthesilea, which would effectively turn the "raw hit" construction into "reconstructed hit". 

The IC book-keeping is already complicated enough, as we cut on same quantities in different places, with varying degree of harshness. If this can be avoided, better, I think. We have a million thresholds in the code...

The point is whether any of those noise-like hits are beneficial for constructing "reconstructed hits" through "corona", "modified corona", etc. Probably they are not useful. In that case, they can and should be eliminated at irene stage already.

As you know well (and as @andLaing reminded us recently), we are already cutting in irene:

- Hits from a SiPM with less than 5 PEs in entire SiPM waveform

- SiPM hits with less than 1 PE per time sample

If this is too loose, we can tune this in irene, without introducing a second set of (higher) thresholds in penthesilea

Ortherwise, if we want to do "reconstruction" on "raw hits" though these new thresholds, then I think it is conceptually cleaner to write only one hit table per penthesilea job, as I mention above

Input from other people on this matter?

**Comment by jjgomezcadenas** [comment]
Cuts in pmaps should be kept at lowest possible values, since they are in practice our hih level raw data. I see no problem whatsoever in raising a threshold later for sipms. I think we are discussing a trivial matter. The need of 1-sipm-hit table is clear, JA and Gonzalo have been working with pmaps because such table was not there, and the flexibilty of a single parameter (sipm threshold) allow for potencial reprocs from pmaps if needed.


Enviado desde mi iPhone
