### ISSUE TITLE
A proposal for an "Analysis repository" (Resurrecting ICARO)

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#595]
Over the last few months we have developed a substantial amount of software that classifies as "IC client". This means:

1. The software (e.g, KrCalib) uses when needed IC functions.
2. But IC does not know anything about the client.

KrCalib is organized in a similar way to IC. Mostly python functions and tests. Notebooks are not allowed there, but collected in a separate repository, KrCalibNB. As usual, it is hard to organize NBs, but this is not the main topic in this issue.

The main topic is the fact that we have other pieces of software (such as the CsTH analysis developed by @jahernando and Gonzalo junior --we need his github user--- that are also clients of IC, but can (and probably should) coexist with KrCalib. CsTH needs the KrCalib maps, but KrCalib may benefit from some common software, e.g, for histograms or dataframe manipulations.

Thus, one possibility is to organize all this analysis code into a repository of analysis (in practice this is still "calibration", rather than analysis, but no reason why analysis itself cannot go in). Thus, IC Analysis RepositOry, or ICARO resurrected.

The previous incarnation of ICARO was an utter failure, but that is understood now. Notebooks are just too hard to organize in git for the time being. But putting together KrCalib and CsTH in ICARO should be straight forward and a proof-of-principle (and test) of how to organize analysis.

Please, usual suspects (@gonzaponte, @jahernando, @msorel, @paolafer, @jmbenlloch, @mmkekic), your opinion.

**Comment by jahernando** [comment]
I agree with your proposal @jjgomezcadenas to have a common repository for the code, client of IC, no NB, that is been used in different reconstruction and analysis studies. Maybe we need to find a name, we fell one with ICARO.

I see it that we need:

1)  to have a commo repository to store our experimental code for reconstruction and analysis, that everyone can criticize, benefit and improve.

2) to reduce the number of dependencies. Now Gonzalo-Diaz and myself we are clients of IC and KrCalib, and the list can follow.

3)  To test new proposal for data-classes, tools, new ideas for reconstruction and analysis.

When one of the studies is completed and we consider it is worth to have it 'officially' we can formalize and properly export it to IC.

For me there are two types of projects, one that is official, bullet-probe and solid (well... software is not anymore solid), like a production line of a factory, and that is IC. And a second type of projects, with clear goals (i.e calibration of the hits), but not a clear path, like R+D in a factory. The disciplines for both are different: for IC, we must force testing and hard-reviews, to garantee good quality data production and validity of the code. While for the second we need to find an equilibrium that discipline does not stop the willingness to explore new ideas. That does not mean that we should not follow the good manners, testing and paying the technical debt periodically, of course.

**Comment by jjgomezcadenas** [comment]
>Maybe we need to find a name, we fell one with ICARO.

I think you mean "failed". But the problem was not the name, but the difficulties to manage Notebooks. I think ICARO is a nice name (and we don't need to invent a new one).

>to reduce the number of dependencies. Now Gonzalo-Diaz and myself we are clients of IC and KrCalib, and the list can follow.

Yes, and @paolafer has her own code somewhere... as the master would say. Outside the cities there is only chaos.

>While for the second we need to find an equilibrium that discipline does not stop the willingness to explore new ideas. That does not mean that we should not follow the good manners, testing and paying the technical debt periodically, of course.

Agreed. Well, my own prototype (KrCalib) has a substantial number of tests, and I do believe that tests are a must, and so are reviews. But indeed, I think is worth to try (again) the old idea of production-quality code (IC)  and development-analysis code (ICARO). This time, however, ICARO is a code repository and NBs are outlaws (so far I still have no practical solution for NBs). 

Unless I hear complains I will work with @jmbenlloch in preparing a new ICARO repository, with lfs and Travis enabled. The repository will include KrCalib and then CsTh. I hope we will be able to merge the code of @paolafer and @jerenner (and others) as well.

**Comment by jahernando** [comment]
@jjgomezcadenas I am re-organizing the code we use, in CsTh, to calibrate SiPMs from pmaps.  I am almost close to pass the suffering of paying the technical debt... There are some code with DataFrames, that could be of some help for Esmeralda and others.

I guess, I wait and committed to the new ICARO, if not, tell me I am putting it in KrCalib.
