### ISSUE TITLE
Change the blob default definition

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#619]
I'm wondering if we should change the functions that return blob energies in `paolina_functions`. The studies of Alberto and myself point to a better definition than the default one. This new definition uses the barycenter of the hits and the hit energies instead of voxel information, as suggested by Michel time ago. Since this is now our new default, I propose to modify the `paolina_functions` functions accordingly. I'm going to do it, as part of the Esmeralda sprint.

**Comment by ausonandres** [comment]
That's a very good idea Paola. I think that nobody is using the old definition currently, and it will simplify Paolina's code a lot.

**Comment by paolafer** [comment]
The change has been done.
