### ISSUE TITLE
Missing run number in `compute xy_position`

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#620]
I've noticed that the function `compute_xy_position` in `components.py` doesn't receive the run number as an argument, and it assumes it's 0. Why is that so? This function depends on the run number because it takes into account the masked SiPMs.

**Comment by gonzaponte** [comment]
I think this is just a matter of taking the run number as the argument and using it in the function, right? I think the reasoning was "the sipms don't change position over time", but didn't considered masking.

**Comment by mmkekic** [comment]
Fixed with #638
