### ISSUE TITLE
New directories in IC

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#66]
I would like to expand the IC directories to include analysis in the following way:

one directory for calibrations /calib
one directory per relevant analysis. Thus, rather than sticking everything into /analysis, I prefer that each analysis main topic has its own folder. Right now we can already define /kripton /na22 and /co56. We can choose between invisible_cities/analysis/kripton or invisible_cities/kripton. I prefer the latest, since the /analysis label is somewhat arbitrary and seems to be that simply hides the visibility of what is going on in the repo.

If you agree with this proposal I would like to submit a pull request creating the directories with a readme.rst where I will add some guidelines concerning the specifics of the analysis. 

Please confirm.

**Comment by jmbenlloch** [comment]
I think the other approach is better (having invisible_cities/analysis directory). It doesn't seem arbitrary to me, but a meaningful structure, in that way we keep things more organized. In any case if you already have the README files ready, you can make the pull request and we can see what kind of things do you expect to be there and how related the different analysis may be.

**Comment by jjgomezcadenas** [comment]
It is true that the different analysis will have correlations. For instance, the na22 and co56 analysis may use the kripton geometry maps, but I think the correlations are weak and well defined. 

True, adding an /analysis directory keeps the top level of invisible cities rather clean. 

What is the opinion of the Jedi?

**Comment by jacg** [comment]
I would prefer not to pollute the top-level directory too much. I am not in a position to judge just how much these different components will have in common. From the directory structure perspective it is not all that important how much they have in common in terms of code, rather whether they conceptually do similar things. From my naive perspective I would propose that they all go into an `analysis` directory.

**Comment by jacg** [comment]
And, in English, krypton is spelt with a Y.

**Comment by jjgomezcadenas** [comment]
Thus, analysis it is by two votes to one (is there a pattern here?) :)!

**Comment by jacg** [comment]
> Thus, analysis it is by two votes to one

Looks more like by 2.5 votes to 0.5, by my reading of the thread.

> is there a pattern here?

We need more data.
