### ISSUE TITLE
New Monte Carlo attribute for particles

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#665]
Currently we are not saving the true information of the final momentum of an MC particle, since it is zero in most of the cases we deal with. However, this is not the case, for instance, if a particle decays in flight. In order to be as general as possible, I would like to add this property, as well, but this introduces an issue of backward compatibility, since we should modify the `MCParticle` class in the event data model, and the function to read particle information. I guess that this is something that at some point was going to happen. How should we deal with this situation?

**Comment by paolafer** [comment]
It has been agreed in the last Santiago-Valencia software meeting that @jmunozv will change the relevant IC code following the simplification of the hdf5 output of nexus. This simplification implies that event data model classes could be not used anymore in the reader and writer true MC functions. In that case, this issue could be dropped.

**Comment by paolafer** [comment]
My understanding is that the `MCParticle` class does not exist anymore, therefore this issue can be closed. @gonzaponte, do you agree?

**Comment by gonzaponte** [comment]
The class does not exist, but has the underlying issue 

> saving the true information of the final momentum of an MC particle

been addressed, disregarded, or something else?

**Comment by paolafer** [comment]
In NEXUS that information is saved now.

**Comment by gonzaponte** [comment]
And the IC side now reads everything as dataframes, so it doesn't need to know what's in there. Ok, closing then.
