### ISSUE TITLE
Esmeralda city changes

### ISSUE THREAD

**Issue by mmkekic** [next-exp/IC#671]
As discussed with @paolafer  and Pau, we agreed to:

- [x]  hard code `norm_strat` option to 'kr' enforcing Esmeralda to always output corrected energy in MeV at Kr scale.

- [x]  Copy whole kdst table coming from Penthesilea without any filtering of events, as well as keeping all the events in Run and MC table. 

- [x] Remove the redundant` 'S1e', 'S1t', 'nS2', 'S2e0', 'S2q0'` from PAOLINA/Summary table.

- [x] Add new load_esmeralda_summary that internally merges relevant kdst information to PAOLINA/Summary table

-  [x] Pass all events through paolina, add out_of_map column in summary table for events that were out of map

@jahernando , @jjgomezcadenas , @gondiaz, @Aretno  fine by you?

**Comment by Aretno** [comment]
Sounds good, yes.

**Comment by jahernando** [comment]
I agree with 1, 2), but not 3)

But I do not seen the purpose of removing the 'redundant' variables in the summary of Paolina.
This is intended to be the analysis n-tuple. Looking to these variables in other tables it is going to be very annoying. In fact, I am using them already, in the summary table, in my analysis of the double-scape peaks.

**Comment by mmkekic** [comment]
@paolafer , we left the option to voxelize using uncorrected energy, in that case drop_voxels energy_threshold can not be given in keV. What do you suggest?

**Comment by paolafer** [comment]
> @paolafer , we left the option to voxelize using uncorrected energy, in that case drop_voxels energy_threshold can not be given in keV. What do you suggest?

In that case I guess that the user must know what's doing, right? And give the right threshold, according to pes.

**Comment by mmkekic** [comment]
Solved with #672 and #681
