### ISSUE TITLE
Detector simulation

### ISSUE THREAD

**Issue by andLaing** [next-exp/IC#691]
The functionality to sort nexus full simulation into buffers or fully simulate the detector response in python (generally referred to as detsim) needs to be integrated into IC.

We propose the following grouping of pull requests to gradually integrate the functionality:
1) Additional source components to read relevant MC info into dataflow
2) New writer to save all the relevant information and add the possibility to split long events into multiple 'triggers'
3) Functions to generate scintillation light and its detection by the sensors
4) Functions to simulate electron drift (diffusion/attachment etc)
5) Functions to simulate EL light and its detection by the sensors
6) Functions to produce buffers and position s1 and s2
7) Utility functions for light level scaling etc
8) Dataflow (city) reading mc hits, simulating detector response, and saving relevant information
9) Dataflow (city) reading full simulation sensor response and production buffers and other relevant info.

All PRs will reference this issue for book keeping.

**Comment by gondiaz** [comment]
10. Functions to manipulate the psf functions.

**Comment by gonzaponte** [comment]
In order to coordinate the PRs, please agree on a common folder for the code that doesn't belong in the cities folder and move your code there (just before the PR is merged, don't do it in between other commits).

**Comment by andLaing** [comment]
In PR #737 I put the new functions in a folder `detector_simulation`. If everyone's happy with that we could use it. If other PRs are accepted before it it'll make things a bit more awkward but it shouldn't be a big problem.

If that name's a bit verbose we could change it in all.

**Comment by gonzaponte** [comment]
Both `detector_simulation` and `detsim` look good to me. I think the detsim name is pretty well known among the software people and it is shorter, which may be nicer to see, but I don't have a strong opinion. Whatever you decide. But I would like all PRs to share this folder before merging them.

**Comment by mmkekic** [comment]
Closed by approving final parts: #742 and #769
