### ISSUE TITLE
event_count repeated in Phyllis result

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#705]
Is Phyllis being used?

Its result contains 4 values, two of which are the same value repeated under different names: `events_in` and `event_count` are both the result of `event_count.future`:

            result = dict(events_in   = event_count     .future,
                          spe         = accumulate_light.future,
                          dark        = accumulate_dark .future,
                          event_count =      event_count.future)

(Additionally, the second `event_count` is misaligned.)

**Comment by jacg** [comment]
... and exactly the same problem appears it Trude.

In fact, the amount of code duplication between Phyllis and Trude looks quite scary! (It's not immediately obvious what the best way of avoiding this would be, but we can definitely do better.)

**Comment by carmenromo** [comment]
Yes, both of them are being used! They compute the spectra for SiPMs (Trude) and PMTs (Phyllis)

**Comment by jacg** [comment]
Oh dear. Is the `event_count` being used?

**Comment by gonzaponte** [comment]
Done in #873 and #880.
