### ISSUE TITLE
Problem with core.testing_utils.assert_dataframes_close

### ISSUE THREAD

**Issue by andLaing** [next-exp/IC#710]
While trying to implement a suggested change to penthesilea_test.py made by @mmkekic in PR #693 I found a problem with `invisible_cities.core.testing_utils.assert_dataframes_close` which occurs when a DataFrame contains a mixture of strings and numbers. Error given is:

`>       xfin = isfinite(x)
E       TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

The function `pandas.testing.assert_frame_equal` seems to have default behaviour which accounts for float accuracy and works in this situation. Maybe we should change our functions to use the pandas implementation?

**Comment by gonzaponte** [comment]
Sounds like something we should definitely do. Can you (or someone else) check that the tests still pass if you replace the implementation of `_compare_dataframes` in testing_utils by one that calls the pandas function?

**Comment by andLaing** [comment]
Another advantage seems to be that the pandas implementation checks the indices (in a lot of the new MC readers we set event number among others as indices) whereas the current IC implementation only checks the columns.

We can do some checks, I'll let @mmkekic assign someone

**Comment by mmkekic** [comment]
Since this seem like a simple change, lets get @MiryamMV  involved? :)

**Comment by MiryamMV** [comment]
I'll handle it! Give me some time xD

**Comment by andLaing** [comment]
I think this was addressed and merged by @MiryamMV in PR #712 so I'll close.
