### ISSUE TITLE
Add Jupiter notebook to environment in manage.sh script?

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#73]
I suggest that we could add jupyter notebook to the environments defined by manage.sh. Most users will eventually work with notebooks and adding the environment in manage.sh avoids that we need to add it later, when they want to run the notebook.  In this way, when they work in the NB repository they will only need to define an extra environment variable (ICNBTDIR) (to make the references to their code and files independent of user details).

If you agree, this can be also added to the next pull request on manage.sh

**Comment by jjgomezcadenas** [comment]
To be specific, I believe that most IC clients will work in analysis. They still need to activate the IC environment (bumpy, sicpy, matplotlib, etc) as well as PYTHONPAT  in to be able to import functions in IC to their NBs. So the IC clients (who are also eventually IC developers) will, anyway, run manage.sh before they go to their NB repo and start to work.

Now, to work with the notebooks they need Jupiter notebook. If this is not already present in the environment, we need to add it "by hand" at this level. In my opinion is not worth it, also because the jupyter NB is powerful and general enough as to deserve to be in the environment from the beginning. 

Thus I believe that it would be nice to add it to our environments.

**Comment by jacg** [comment]
`ICNBTDIR` is really getting too cyptic. Something like `IC_NOTEBOOK_DIR` would be better.

If I understand you correctly you want the following two changes

1. Add jupyter to the conda envs created by `manage.sh`
1. Decide on some directory name where the notebooks will go *inside* `$ICTDIR` and make `IC_NOTEBOOK_DIR` point there.

Is this correct?

In the meantime let's see how much [my jupyter branch](https://github.com/jacg/IC/tree/jupyter) adds to the [Travis build time](https://travis-ci.org/jacg/IC/builds/191883519).

**Comment by jacg** [comment]
BTW, rather than starting an issue, you could create a branch, maybe even with a pull request: code sometimes communicates more clearly what you mean that prose.

**Comment by jjgomezcadenas** [comment]
1) What about NBDIR?
2) Yes, I suggest to add Jupyter to the conda envscreated by manage.sh 
3) NO, I don't want the NBs to live in IC. We have in nextic a second repository, called Notebooks, which can be forked by people, fully devoted to Notebooks. 

The work flow for developers then would be.
1) run the manage.sh script to activate their python env and variables.
2) if they want to work in IC (scripts, text) they are all set to go.
3) if they want to work in NB, they switch to their fork of NB repo, then run another script there, which is a simpler version of manage.sh. 

This script allows them to switch python environment if they desire so and defines the additional variable NBDIR, which is needed because the NB repository will also include "demonstration"  files. I think those files are needed in the repository to guarantee that the NB runs the same for everybody (it the files live in local disks, then one is never sure what is the input). Of course, the users will not be uploading big files to the repository, normally a few events are OK for demonstration at the reconstruction level (diomira/isidora) and a few hundred or thousand at analysis levels (but analysis runs over PMAP files which are very slim). 

To repeat, most of the stuff that the users do in the Notebook repo will always stays in their local forks, and only clean, well thought NBs will be uploaded to the central repo. 

But definitively, I don't want the Notebooks in IC, which is to be kept as slim and gracile as possible. The whole idea of the NB is that the developer "translates" his NB rumblings to clean scripting code and functions that will go to the corresponding place in IC.

For example, consider the calibration of PMTs. This will go into its own directory in invisible_cities, at the same level than cities, core, etc (and one level above analysis, since calibration is general (as the reconstruction done in cities is also general) while analysis contains many possible specifics (krypton, na22, co56...).

The calibration of PMTs and SiPMs has already been done in the old repo by Jose Angel and students. JA ha a pretty nice NB that shows and documents the whole process. This NB is an ideal candidate for the Notebooks repository. 

Next, Joe Angel has to write a script, say calib/calibrate_pmts.py, he needs to add 
calibrate_pmt_test.py and any file needed for the test to the files directory (plus any extra general function needed for the calibration to core), then prepare a pull request. Most likely, after the whole process is over, he will further improve his notebook and make another pull request to the NB directory. I think this is a pretty nice cycle. 

I suggest that the docs in IC are those generated by Sphinx or similar.

**Comment by jacg** [comment]
> What about NBDIR?

Far too cryptic. How about `IC_NOTEBOOK_DIR` ?

**Comment by jjgomezcadenas** [comment]
We have already taken NBDIR and written diomira.ipynb using it. I like NBDIR better, because is concise (meaning obvious for me NB = notebook).

**Comment by jacg** [comment]
The thing with such names is that they have to be obvious 
- to everyone
- for all time 
- in a broader context (e.g. when seen in the output of `env`)

and not merely

- their inventor
- 3 seconds after he invented it
- in isolation

You are injecting this variable into a single namespace in your shell's environment: Not identifying it explicitly as something to do with `IC` is a mistake.

**Comment by jjgomezcadenas** [comment]
I still fail to get why ICDIR is OK and NBDIR is not OK. Sorry if I am too thick.

**Comment by jacg** [comment]
Well, `ICDIR` is the **dir** in which **IC** stuff goes. While `NBDIR` is the **dir** where **N**ota **B**ene goes?

`ICDIR`'s major saving grace is that it contains `IC` to indicate that it has something to do with **IC**. I trust that you agree that, if these were python variables, you would stick them all in the same namespace. Shell variable names aren't namespaced, so we have to encode the namespace in the variables themselves. Please pick a name that starts with `IC`.

**Comment by jjgomezcadenas** [comment]
Ay, ay, sir. 

I am changing everything to IC_NOTEBOOK_DIR.
