### ISSUE TITLE
Two small changes in manage.sh

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#74]
Here is a proposal for two small changes in manage.sh (I can do them, but let's agree that this is OK first).

1) in function ic_env

    echo setting PYTHONPATH
    export PYTHONPATH=$ICTDIR:$PYTHONPATH

has the side effect that each time the script is executed (and it can be executed many time in the same region) the variable PYTHONPATH grows (although it points always to the same place, e.g, the top IC directory). 

On the other hand, I believe that PYTHONPATH should point exclusively to top level IC and nothing else when working in IC (this is the situation currently). Then, one could simply do instead:

   echo setting PYTHONPATH
    export PYTHONPATH=$ICTDIR

2) In the same function: 

    echo setting ICDIR
    export ICTDIR=`pwd`

    echo setting ICTDIR
    export ICDIR=$ICTDIR/invisible_cities/

    echo setting PYTHONPATH
    export PYTHONPATH=$ICTDIR:$PYTHONPATH

I think it would be better:

  
    export ICTDIR=`pwd`
   echo ICDIR has been set to $ICDIR

(etc for all the others)

**Comment by jacg** [comment]
> Here is a proposal for two small changes in manage.sh (**I can do them**, 

Then assign yourself, not someone else!  Attract people's attention with `@username` anywhere in the github comment.

> I believe that PYTHONPATH should point exclusively to top level IC and nothing else when working in IC

Agreed.

> I think it would be better:
>
>     export ICTDIR=`pwd`
>     echo ICDIR has been set to $ICDIR

Good idea (as long as the names actually match on the two lines :-)

Now, it would be nice if we could deactivate the non-conda part of the IC environment (analagously to conda deactivation). In practice, I don't think it's worth our time to do this: 99.9% of the time we'll just close the shell.
