### ISSUE TITLE
Diomira speed

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#76]
We have now a rather stable version of DIOMIRA which runs at ~0.5 events/second in a fast processor (I-7 at 3.1 GHz) on MacOS X. 

I propose to investigate:
1) dependence of speed with system (e.g, LinUX,  lxplus machines at CERN)
2) dependence on compressor parameters. Currently RWF are 150 kb per event with ZLIB4 and MCRD files are 110 kb per event. Any major speed gain if we decrease a bit compression? Any major speed lost if we increase it?

**Comment by jmbenlloch** [comment]
For the Kr run at CERN I have run over 92 files, 10k evts/file, and this are the times in seconds registered:

min: 7394
max: 17870
avg: 10877.076087
std: 1950.35533682

So, we have 1.08 +- 0.2 s/evt at CERN. All those 92 jobs have run concurrently, therefore we can have ~1Mevts in ~3 hours.
