### ISSUE TITLE
Travis changes

### ISSUE THREAD

**Issue by mmkekic** [next-exp/IC#763]
Travis is completely moving to travis-ci.com domain as given in the notification:

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

I guess the owner of a repository Dr @jmbenlloch would need to fix our travis account. This might also be related to Travis not being built for PR #761.

**Comment by jacg** [comment]
We should probably think about switching from Travis to GitHub Actions, anyway.

**Comment by mmkekic** [comment]
Hmm, seems GitHub Actions allows for up to 2000 minutes a month for private repositories for free, this could be interesting for nexus as well  @paolafer , @jmalbos ?

**Comment by jmbenlloch** [comment]
I have transfer our repositories from travis-ci.org to travis-ci.com. I have also manually [triggered a build of the master](https://github.com/next-exp/IC/runs/1681743874) and [the latest PR](https://github.com/next-exp/IC/pull/764#partial-pull-merging), both of them worked.

Everything seems to be working now. I have updated the required status check for our PRs, now it is called "Travis CI - Pull Request". In the older PRs it has not been triggered automatically, so the owner of each PR should push again the branch to force travis-ci.com to run the build.

That should work for now, in the longer term it will probably be better to switch to GitHub Actions as @jacg said. I have other tasks now, but I will try to have a look at it in the future.

**Comment by mmkekic** [comment]
Resolved by #768
