### ISSUE TITLE
Get Event Numbers from MC files

### ISSUE THREAD

**Issue by jmunozv** [next-exp/IC#771]
Currently, this action is implemented in `invisible_cities.io.mcinfo_io.get_event_numbers_in_file(...)`

For simulations with the new nexus persistency format, it is extremely slow. As an example, to get the list of the 4 event_ids contained in a NEXT100 bb0nu full simulation file takes almost 1 second. The reason is that this function checks 'hits', 'particles' and 'sns_response' tables to look for unique event_ids in them.

The idea is to simplify and speed up this function given that:

- There are no events with hits and no particles. In Geant4 all hits belong to a particle, and these particles are aways stored in nexus.
- Something similar happens with sns_response, although in this particular case, optical photons (the only particles seen by our sensors) can be stored in the simulation or not.

If these statements are correct (please experts in nexus simulations @jmalbos and @paolafer confirm) my claim is that the function should:
1. If there are stored particles, return the unique event_ids from this table.
2. If not, return the unique event_ids from sns_response.
 
Some preliminary checks yield a time consumption reduction higher than a factor 100 for previous example.

**Comment by paolafer** [comment]
I think that this issue can be closed, since it was solved in PR #772.

**Comment by gonzaponte** [comment]
Closing as solved in #772.
