### ISSUE TITLE
Create a bash command argument completion file for `manage.sh`

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#78]
Our `manage.sh` script is acquiring (#77)  a large number of long and inconvenient to type command arguments. It would benefit immensely from completion help from the shell. I get the impression that most of us are using `bash` or some derivative. Let's provide a file which teaches `bash` how to complete `manage.sh`'s arguments for us.

How this can be done seems to be described [here](http://www.tldp.org/LDP/abs/html/tabexpansion.html).

Once made, this file can be sourced to enable the completion. You could do this in your `.bashrc` or similar.

**Comment by jjgomezcadenas** [comment]
Earth talking to Galactica. I hear that Capitan JJ won't do it. I guess admiral JCK is busy next couple of weeks. Shall we assign democratically to lieutenant JMB?

**Comment by jacg** [comment]
Get in the habit of @-mentioning people who you want to read the message. In this case mentioning @jmbenlloch would have been a good idea.

I suggest that he assign himself, if he feels like taking it on. Otherwise, it can sit there in the list of issues until somebody takes pity on it, or someone thinks it needs to be given a higher priority. It's possibly not of the highest priority at the moment.

**Comment by jjgomezcadenas** [comment]
Ay, Ay, sir!

As for JM he is sitting by my side, so he has taken notice! And he is assigning himself to the task. He is indeed pretty busy, but also pretty fast, so no worries.
