### ISSUE TITLE
Analysis: argument in favor of independent repository

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#83]
The last couple of days have made obvious an important difference between the workflow in IC and in Notebooks, which can be summarised (simplified) like this:

In IC the developer "follows the main repository". This makes sense, since IC is primarily concerned about reconstruction, from low level objects to high level objects. This is done by chaining cities, and adding auxiliary functions to core. Plus tests. The developers are somewhat generalists, and can work often in any aspect of the reconstruction. 

The workflow calls for rebasing often into the main directory, so that there is never too much divergence between the fork of a given developer and the main repository. 

Instead, as we have "discovered" in the last couple of days, the workflow for Notebooks is different. Developers are mainly concerned with their own analysis, and in general not interested in what is happening in other analysis. Thus, a workflow with a Develop and a Deliver branch seems OK and git gives us the tools to facilitate this.

It turns out that Notebooks mimic quite well what will happen in Analysis. In fact, the developers will most likely prepare a draft version of their analysis in the NBs and then translate to scripts. But still the WF is the same. They will want to work for a long time in a Develop branch, running in their own fork and eventually export the results of their work to Deliver. 

This brings me to the proposal of creating a separate directory for analysis. It has no real cost, since the Analysis repo could import all IC modules by simply setting PYTHONPATH as we do for Notebooks. It would separate Analysis (which has less intrinsic tests, more contributors, and is in general messier) from Reconstruction (that must be crystal clear), and it would permit a simple workflow (with no rebases, etc.) for people just interested in analysis. 

Your opinion, @jacg and @jmbenlloch

**Comment by jacg** [comment]
I haven't found the time necessary to read and think about this. Can it wait until Friday afternoon?

**Comment by jjgomezcadenas** [comment]
We can, but if you have the time we can also have lunch together…

**Comment by jacg** [comment]
Yes, fine. 12 at the Training Centre, or 12:05 at Resto 2.

**Comment by jjgomezcadenas** [comment]
12:05 resto 2

**Comment by jjgomezcadenas** [comment]
Agreed: We create an analysis repository called ICARO.
