### ISSUE TITLE
How to handle static html produced by NBs

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#85]
I have investigated a bit GitPages and does not appear to be a specially intelligent solution. 

The reason is this: GitPages is yet another GitHub repository, with some tweaks to present pretty pages if the use wants to put the work on it. But they are still keeping the .html docs under GitHub! 

Thus, using gitpages is not different conceptually from just uploading the html files to our repository and take advantage of the git capability to read them directly. If we are going to put html pages in git, better to do so in our own repository that start some new repository just for that (with all the added overhead). 

Perhaps they can be put somewhere else, but is not obvious where. 

My proposal is that we keep the html in our repository unless we find a better solution soon. The whole purpose of the NBs is that they can be read, and currently, since we are stripping them and not pushing the html they are not useful.

**Comment by jjgomezcadenas** [comment]
See for example:
https://jjgomezcadenas.github.io/diomira.html

As you can see, the special GitHub repository associated with GitPages serves html files... but it is always through git. In this sense, I think that the most economic solution for us is to simply put the html files in a /doc folder and push them to the repository.

**Comment by jacg** [comment]
> I think that the most economic solution for us is to simply put the html files in a /doc folder and push them to the repository.

No, *no*, **no**, NOOOOOO!

Unless you write these HTML files yourself. But given that these HTML files are generated products, they should not go in a repo. Repos should only contain source, not stuff which is generated from that source. Like all rules, there are times when this rule should be broken, but I am confident that, once I get some time to look at this, it will turn out that this is not one of the rare situations where this rule should be broken.

**Comment by jjgomezcadenas** [comment]
OK! We wait for the Jedi wisdom.

**Comment by jjgomezcadenas** [comment]
Issue understood, html files will be recorded in an independent non.version controlled served (the Gallery).
