### ISSUE TITLE
Remove default binning in `Buffy`

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#857]
This line is extremely dangerous as it uses a default value that the user surely is not aware of and probably doesn't understand. This has caused troubles in the past. I believe it doesn't cause them anymore, but it's better to be safe than sorry.

https://github.com/next-exp/IC/blob/86e39c483455e07e644931824294674dec78a0d9/invisible_cities/cities/buffy.py#L165

**Comment by paolafer** [comment]
What do you suggest we do with that? Return `None`, remove that function and use the exception directly in the code...?

**Comment by gonzaponte** [comment]
I believe now all nexus files contain the binning, right? If so I would raise an exception if the values are not found.

**Comment by paolafer** [comment]
I don't know if that's what you mean, but could we simply remove 

` return 25 * units.ns, 1 * units.mus `?
The exception is raised inside the for-loop. I dont' understand how that function works exactly.

**Comment by paolafer** [comment]
I see that in the current version of the function, if no binnings are found in any of the files, the default values are returned. If we want to change that (sensible), we have to modify the test that deals with empty tables (`test_buffy_filters_empty`). There's no description of what the test is supposed to ensure, so I'm a bit puzzled about how to change the test.
