### ISSUE TITLE
Should  `manage.sh` be replaced with a makefile?

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#88]
If we can get `make` to work with the commands than need sourcing, then we should probably do it.

**Comment by jacg** [comment]
Our `manage.sh` script serves as a single point of reference for how the IC components are installed, configured, compiled, tested and so on.

The problem with `manage.sh` is that it is a non-standard solution that smacks of NIH.

Being a python project, a `setup.py` is a rather obvious alternative. The problem is that it requires a pre-installed python interpreter, while one of the tasks that `manage.sh` performs is installation of python itself. So `setup.py`, if used, will need to be augmented with a separate utility which installs python (which itself requires installing conda and preparing the conda environment).

A second problem is that of setting environment variables. With `setup.py` we could overcome this hurdle with

    source `setup.py` <command>

and have `setup.py` print out the env-setting shell commands for  such commands. Though commands which need to carry out other steps (which result in something being written to stdout) as well as setting environment variables are going to be painful to deal with.

So, how about make? The advantages are

- NIH, so we're not re-inventing the wheel
- No bootstrapping problem: a usable version will be installed pretty much everywhere
- `manage.sh` contains a large number of commands which perform overlapping subsets of tasks; the `make` dependency system should reduce this need

The downsides:

- not obvious how to resolve the sourcing problem.

For now, `manage.sh` works, and I don't have time to look into this in any depth. But we should be careful not to let our re-invention of the wheel snowball into a monster.

**Comment by jjgomezcadenas** [comment]
I believe that practice dictates that this is not gonna happen any time soon. Can we close this issue, at least for the time being?
