### ISSUE TITLE
Reorganization of the reco folder

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#885]
I would like to complete the job done in PR #707 but never finished, meaning, reorganizing the `reco` folder.
At the moment this folder contains very different functions and some of them are not related to reconstruction, from my point of view.

My proposal is the following: 

1. `sensor_functions` and `spe_response` are part of the MC simulation of the events, rather than the reconstruction, therefore they should go to a dedicated folder (maybe a new `mcsim`?). 
2. `tbl_functions` are very generic functions to deal with tables, so they could go to `core`.
3. I'm not sure about `wvf_functions`; they deal with waveforms, so they are part of the reconstruction in a way.
4. Same about the two calib files. Calibration can be considered part of the reconstruction, so they can stay here.

Opinions?

**Comment by gonzaponte** [comment]
Thank you for addressing this.

1. Agreed. I would merge it with the `detsim` directory and name it `sim` or maybe leave the same name. I would also include other parts of the code such as the noise sampler in core/random_sampling which has been living there for a while.
2. Agreed.
3. I would also keep this one in `reco`
4. I would move these to a new `calib` folder. The code for the Kr maps could also go in there.

**Comment by paolafer** [comment]
Maybe I'm missing something here, but it looks like `spe_response` is not imported anywhere in IC, except for its own test file. Is that correct?

**Comment by gonzaponte** [comment]
You are right. I believe these were functions used in external calibration programs. The same used to happen with fit_functions in core. We should check if someone is still using them.

@joshgrocott, are you using functions from `spe_response.py`?

**Comment by joshgrocott** [comment]
Hi Gonzalo,

Yes, namely the calibration scripts use scaled_dark_pedestal. Is there a problem?

Regards,
Josh
________________________________

**Comment by gonzaponte** [comment]
> Is there a problem?

Nope. Just notice that when this is merged (and you update your local IC) you will have to adjust the imports in your scripts.

**Comment by gonzaponte** [comment]
Also, this indicates that spe_response belongs to calib, not detsim.

**Comment by bpalmeiro** [comment]
As the plan, I'd say, is to eventually incorporate said external process into IC, we can think of incorporating it into the calibration folder so it's kinda self-contained. Maybe we can even consider changing the name to accommodate.
