### ISSUE TITLE
Structure of the analysis repository (anatomy of ICARO)

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#90]
The analysis repository (ICARO) will contain a number of essentially independent analysis (often but not exclusively based on calibration radioactive sources). Describe the organisation of the repository and the proposed workflow.

**Comment by jjgomezcadenas** [comment]
@gonzaponte can you describe the new structure of ICARO?

**Comment by gonzaponte** [comment]
I will... as soon as I have some time for it.
