### ISSUE TITLE
Structure of the reconstruction repository (anatomy of IC)

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#91]
The IC repository will contain the reconstruction program of NEW/NEXT. Describe the structure and workflow on IC.

**Comment by jjgomezcadenas** [comment]
Regarding the structure of IC, here a proposal:

1) The directory *core* lumps together rather different animals. I propose to split of *core* in two separate directories:
a) *core* which would keep what I think are really core modules: configure, core_functions, exceptions, log_config, random_sampling and system_of_units, mpl_f (plus testing modules and cython modules)
b) *reco* which would, for now, get all the rest: nh5, params, peak_functions, pmaps_functions, tbl_f, wfm_f, mctrk_f  (plus testing and cython)

Opinons?

**Comment by jacg** [comment]
This specific sub-issue has it's own issue now: #150.
