### ISSUE TITLE
How do we want to distribute or package IC?

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#97]
At the moment we have a very simple `setup.py` which we invoke with the `develop` command in order to compile the cython modules. This relults in the products (not only the `.so` files which are the actual modules, but also the Cython-generated `.c` files, which are just intermediate garbage by-products) being placed in our source tree. This has served us just fine as an initial quick and dirty solution to allow us to get on with writing the code, but it's not a very good long term solution.

Who do we expect to be using IC, and how do we expect them to install it?

Once we know the answer to the last question, we should decide how to move forward with our `setup.py`.

**Comment by jjgomezcadenas** [comment]
Our first clients will be a “smallish groups of developers”. Jose Angel and students, Paola,  Josh and Alex. Perhaps 5 or 6 guys. On the other hand, IC is gonna become the official reconstruction in NEXT very, very soon, so I believe we must assume we are preparing this as the official NEXT software. 

The software will be installed in Valencia (neutrinos) Canfranc, CERN and in the laptops of about every body (many of them are Macs).

**Comment by jacg** [comment]
> The software will be installed in Valencia (neutrinos) Canfranc, CERN and in the laptops of about every body

How do we expect them to install the software for their use?

I assume that the majority of these will be users and will not contribute to development at all.

> (many of them are Macs).

Just as well that we're building in Travis on OS X !

**Comment by jjgomezcadenas** [comment]
> On 21 Jan 2017, at 20:34, jacg <notifications@github.com> wrote:
> 
> The software will be installed in Valencia (neutrinos) Canfranc, CERN and in the laptops of about every body
> 
> How do we expect them to install the software for their use?
> 
> 
As we did, install conda and then ran manage and setup. It is rather straight forward (nothing, really, compare with installing Art, which actually then can’t do in their laptops…)

**Comment by jacg** [comment]
If we expect the software to be installed from git, then I see two consequences

1. `setup.py` serves puerly to compile the code for the users, in situ, with the `develop` command: we never need build outside the source tree, we never need to create tarballs, eggs, wheels, or any other form of packaging and distibuting the code. This implies that I can remove my `build` branch.

1. We are doing continuous delivery/deployment and do not need any releases at all. This implies that we should remove the `nextic/release` branch. We simply have to ensure that `nextic/master` always builds correctly (and is thoroughly tested by the automatic tests).

Unless I hear anything to the contrary within the next week, I will remove the `nextic/release` branch.

**Comment by jjgomezcadenas** [comment]
Master or release? We do not need release branch, but we still need master branch…

**Comment by jacg** [comment]
Sorry, brain fart. Edited.

**Comment by jacg** [comment]
Conclusion: Continuous deployment via github. No packaging required.
